import json

HADITHS = [
    {"id":1,"narrator":"Umar ibn al-Khattab","source":"Bukhari","no":"1",
     "en":"Actions are judged by intentions; every person gets what they intended.",
     "ru":"Поистине, дела оцениваются по намерениям, и каждому — то, что он намеревался.",
     "tr":"Ameller niyetlere göredir; herkes niyet ettiğini elde eder.",
     "fr":"Les actes ne valent que par les intentions; chaque personne obtient ce qu'elle a voulu."},
    {"id":2,"narrator":"Uthman ibn Affan","source":"Bukhari","no":"5027",
     "en":"The best of you are those who learn the Quran and teach it.",
     "ru":"Лучший из вас тот, кто изучает Коран и обучает ему других.",
     "tr":"En hayırlınız Kur'an'ı öğrenen ve öğretendir.",
     "fr":"Le meilleur d'entre vous est celui qui apprend le Coran et l'enseigne."},
    {"id":3,"narrator":"Abu Malik al-Ashari","source":"Muslim","no":"223",
     "en":"Purity is half of faith.",
     "ru":"Чистота — половина веры.",
     "tr":"Temizlik imanın yarısıdır.",
     "fr":"La pureté est la moitié de la foi."},
    {"id":4,"narrator":"Anas ibn Malik","source":"Bukhari","no":"13",
     "en":"None of you truly believes until he loves for his brother what he loves for himself.",
     "ru":"Никто из вас по-настоящему не уверует, пока не пожелает брату того же, чего желает себе.",
     "tr":"Hiçbiriniz, kardeşi için kendisi için istediğini istemedikçe gerçek iman etmiş olmaz.",
     "fr":"Aucun de vous ne croit vraiment tant qu'il n'aime pas pour son frère ce qu'il aime pour lui-même."},
    {"id":5,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6114",
     "en":"The strong man is not the one who wrestles others down; he is the one who controls himself when angry.",
     "ru":"Сильный — не тот, кто побеждает в борьбе, а тот, кто владеет собой в гневе.",
     "tr":"Güçlü kişi güreşte yenen değil, öfke anında kendine hâkim olandır.",
     "fr":"Le fort n'est pas celui qui terrasse les autres; c'est celui qui se maîtrise dans la colère."},
    {"id":6,"narrator":"Abu Musa al-Ashari","source":"Bukhari","no":"69",
     "en":"Make things easy and do not make them difficult.",
     "ru":"Облегчайте, а не затрудняйте.",
     "tr":"Kolaylaştırınız, zorlaştırmayınız.",
     "fr":"Facilitez les choses, ne les compliquez pas."},
    {"id":7,"narrator":"Abdullah ibn Masud","source":"Bukhari","no":"527",
     "en":"The best of deeds is the prayer performed on time.",
     "ru":"Лучшее из дел — молитва, совершённая в своё время.",
     "tr":"Amellerin en faziletlisi namazı vaktinde kılmaktır.",
     "fr":"La meilleure des actions est la prière accomplie en son temps."},
    {"id":8,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6018",
     "en":"Speak good or remain silent.",
     "ru":"Говори благое или молчи.",
     "tr":"Hayır söyle ya da sus.",
     "fr":"Dis ce qui est bon ou garde le silence."},
    {"id":9,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6019",
     "en":"Whoever believes in Allah and the Last Day should honor his guest.",
     "ru":"Кто верует в Аллаха и Судный день, пусть чтит своего гостя.",
     "tr":"Allah'a ve ahiret gününe iman eden misafirine ikram etsin.",
     "fr":"Que celui qui croit en Allah et au Jour dernier honore son hôte."},
    {"id":10,"narrator":"Abdullah ibn Amr","source":"Tirmidhi","no":"1924",
     "en":"The merciful are shown mercy by the Most Merciful. Be merciful to those on earth.",
     "ru":"Милостивые удостоятся милости Милостивого. Будьте милостивы к тем, кто на земле.",
     "tr":"Merhametlilere Allah da merhamet eder. Yeryüzündekilere merhamet edin.",
     "fr":"Les miséricordieux reçoivent la miséricorde du Très Miséricordieux."},
    {"id":11,"narrator":"Abu Dharr","source":"Tirmidhi","no":"1956",
     "en":"Smiling at your brother is charity.",
     "ru":"Улыбка брату твоему — это садака.",
     "tr":"Kardeşine gülümsemen sadakadır.",
     "fr":"Sourire à ton frère est une aumône."},
    {"id":12,"narrator":"Abu Hurayrah","source":"Muslim","no":"2956",
     "en":"The world is a prison for the believer and a paradise for the disbeliever.",
     "ru":"Мир — тюрьма для верующего и рай для неверующего.",
     "tr":"Dünya müminin zindanı, kâfirin cennetidir.",
     "fr":"Le monde est une prison pour le croyant et un paradis pour le mécréant."},
    {"id":13,"narrator":"Abdullah ibn Amr","source":"Ibn Majah","no":"425",
     "en":"Do not waste water, even if you are at a flowing river.",
     "ru":"Не расточай воду, даже если черпаешь из текущей реки.",
     "tr":"Akan nehirden su alsan bile israf etme.",
     "fr":"Ne gaspille pas l'eau, même si tu puises dans une rivière qui coule."},
    {"id":14,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2989",
     "en":"A good word is charity.",
     "ru":"Доброе слово — это садака.",
     "tr":"Güzel söz sadakadır.",
     "fr":"Une bonne parole est une aumône."},
    {"id":15,"narrator":"Aisha","source":"Bukhari","no":"6464",
     "en":"The most beloved deeds to Allah are those done consistently, even if they are few.",
     "ru":"Самые любимые Аллахом дела — те, что совершаются постоянно, пусть даже немного.",
     "tr":"Allah'a en sevimli ameller az da olsa devamlı yapılanlardır.",
     "fr":"Les actes les plus aimés d'Allah sont ceux accomplis régulièrement, même peu nombreux."},
    {"id":16,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2442",
     "en":"The best of people is the one who is most beneficial to others.",
     "ru":"Лучший из людей — тот, кто приносит наибольшую пользу другим.",
     "tr":"İnsanların en hayırlısı, insanlara en çok faydalı olandır.",
     "fr":"Le meilleur des hommes est celui qui est le plus utile aux autres."},
    {"id":17,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"5978",
     "en":"Paradise lies at the feet of mothers.",
     "ru":"Рай находится у ног матерей.",
     "tr":"Cennet annelerin ayakları altındadır.",
     "fr":"Le paradis se trouve sous les pieds des mères."},
    {"id":18,"narrator":"Abu Hurayrah","source":"Muslim","no":"2564",
     "en":"Do not be angry, and Paradise is yours.",
     "ru":"Не гневайся, и тебе уготован рай.",
     "tr":"Kızma, sana cennet var.",
     "fr":"Ne te mets pas en colère, et le paradis t'est promis."},
    {"id":19,"narrator":"Anas ibn Malik","source":"Tirmidhi","no":"1987",
     "en":"Whoever shows mercy will be shown mercy by the Most Merciful.",
     "ru":"Тот, кто проявляет милосердие, удостоится милосердия Всемилостивого.",
     "tr":"Merhamet eden, Merhametliler Merhametlisi'nin merhametine nail olur.",
     "fr":"Celui qui fait preuve de miséricorde recevra la miséricorde du Très Miséricordieux."},
    {"id":20,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6116",
     "en":"Whoever does not show mercy will not be shown mercy.",
     "ru":"Тот, кто не проявляет милосердия, не удостоится милосердия.",
     "tr":"Merhamet etmeyene merhamet edilmez.",
     "fr":"Celui qui ne fait pas preuve de miséricorde ne recevra pas de miséricorde."},
    {"id":21,"narrator":"Abu Hurayrah","source":"Muslim","no":"2162",
     "en":"Spread the greeting of peace; it spreads love among you.",
     "ru":"Отвечайте на приветствие мира; оно распространяет любовь между вами.",
     "tr":"Selamı yayın; aranızda sevgiyi artırır.",
     "fr":"Répandez le salut de paix; cela propage l'amour entre vous."},
    {"id":22,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"5199",
     "en":"The best of you is the one who is best to his family.",
     "ru":"Лучший из вас — тот, кто лучше всех относится к своей семье.",
     "tr":"En hayırlınız ailesine en iyi davananınızdır.",
     "fr":"Le meilleur d'entre vous est celui qui est le meilleur envers sa famille."},
    {"id":23,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1461",
     "en":"Give charity without delay, for it stands in the way of calamity.",
     "ru":"Подавайте милостыню без промедления, ибо она стоит на пути несчастий.",
     "tr":"Sadakayı geciktirmeden verin; zira o belanın önünde durur.",
     "fr":"Donnez l'aumône sans tarder, car elle se dresse devant le malheur."},
    {"id":24,"narrator":"Anas ibn Malik","source":"Bukhari","no":"2518",
     "en":"Help your brother whether he is an oppressor or oppressed.",
     "ru":"Помоги своему брату, будь он угнетателем или угнетённым.",
     "tr":"Kardeşine yardım et, ister zalim ister mazlum olsun.",
     "fr":"Aide ton frère qu'il soit oppresseur ou opprimé."},
    {"id":25,"narrator":"Abu Hurayrah","source":"Muslim","no":"2699",
     "en":"Whoever travels a path seeking knowledge, Allah will ease his path to Paradise.",
     "ru":"Кто идёт по пути в поисках знаний, тому Аллах облегчает путь в рай.",
     "tr":"İlim yolunda yürüyene Allah cennete giden yolu kolaylaştırır.",
     "fr":"Quiconque emprunte un chemin pour acquérir la connaissance, Allah lui facilitera le chemin vers le paradis."},
    {"id":26,"narrator":"Abdullah ibn Abbas","source":"Bukhari","no":"6412",
     "en":"The upper hand is better than the lower hand; give before you are in need.",
     "ru":"Дающая рука лучше берущей; давай прежде, чем окажешься в нужде.",
     "tr":"Veren el alan elden hayırlıdır; ihtiyaç duymadan önce ver.",
     "fr":"La main qui donne vaut mieux que la main qui reçoit."},
    {"id":27,"narrator":"Abu Hurayrah","source":"Bukhari","no":"5673",
     "en":"Visit the sick, feed the hungry, and free the captive.",
     "ru":"Навещайте больных, кормите голодных, освобождайте пленных.",
     "tr":"Hastaları ziyaret edin, açları doyurun, esirleri serbest bırakın.",
     "fr":"Rendez visite aux malades, nourrissez les affamés et libérez les captifs."},
    {"id":28,"narrator":"Aisha","source":"Muslim","no":"746",
     "en":"The most beloved prayer to Allah after the obligatory is the night prayer.",
     "ru":"Самая любимая Аллахом добровольная молитва после обязательных — ночная.",
     "tr":"Farz namazlardan sonra Allah'a en sevimli namaz gece namazıdır.",
     "fr":"La prière la plus aimée d'Allah après les obligatoires est la prière de nuit."},
    {"id":29,"narrator":"Abu Hurayrah","source":"Bukhari","no":"3186",
     "en":"Every act of kindness is charity.",
     "ru":"Каждое доброе дело является садакой.",
     "tr":"Her iyilik sadakadır.",
     "fr":"Tout acte de bonté est une aumône."},
    {"id":30,"narrator":"Abu Said al-Khudri","source":"Bukhari","no":"1376",
     "en":"Whoever believes in Allah and the Last Day, let him say good or remain silent.",
     "ru":"Кто верует в Аллаха и Судный день, пусть говорит благое или молчит.",
     "tr":"Allah'a ve ahiret gününe iman eden hayır söylesin ya da sussun.",
     "fr":"Que celui qui croit en Allah et au Jour dernier dise ce qui est bon ou garde le silence."},
    {"id":31,"narrator":"Abu Hurayrah","source":"Tirmidhi","no":"2516",
     "en":"This world is cursed and what is in it is cursed, except the remembrance of Allah.",
     "ru":"Этот мир проклят, и то, что в нём проклято, кроме поминания Аллаха.",
     "tr":"Bu dünya lanetlidir; Allah'ın zikri ve ona yardımcı olan şeyler hariç.",
     "fr":"Ce monde est maudit et ce qu'il contient est maudit, sauf le souvenir d'Allah."},
    {"id":32,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"6094",
     "en":"Lower your gaze and guard your private parts.",
     "ru":"Опускай взор и оберегай своё целомудрие.",
     "tr":"Gözünü koru ve ırzını muhafaza et.",
     "fr":"Baisse le regard et préserve ta chasteté."},
    {"id":33,"narrator":"Abu Hurayrah","source":"Muslim","no":"2588",
     "en":"Whoever removes a worldly hardship from a believer, Allah will remove from him a hardship on the Day of Resurrection.",
     "ru":"Кто избавит верующего от мирской беды, того Аллах избавит от беды в День воскресения.",
     "tr":"Bir müminden dünyevi bir sıkıntıyı gideren kimsenin, Allah kıyamet günü sıkıntısını giderir.",
     "fr":"Quiconque soulage un croyant d'une épreuve mondaine, Allah le soulagera au Jour de la Résurrection."},
    {"id":34,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6011",
     "en":"Spread peace among yourselves.",
     "ru":"Распространяйте мир между собой.",
     "tr":"Aranızda selamı yayın.",
     "fr":"Répandez la paix entre vous."},
    {"id":35,"narrator":"Abu Hurayrah","source":"Bukhari","no":"5765",
     "en":"Envy is permitted only for two: one given wealth who spends it rightly, and one given wisdom who acts by it.",
     "ru":"Зависть допустима лишь в двух случаях: к богатому, тратящему праведно, и к мудрому, действующему согласно мудрости.",
     "tr":"İki kişiye gıpta edilir: birine Allah mal vermiş hak yolunda harcıyor, diğerine hikmet vermiş.",
     "fr":"L'envie n'est permise que dans deux cas: envers celui qui dépense sa richesse justement, et celui qui agit avec sagesse."},
    {"id":36,"narrator":"Abdullah ibn Masud","source":"Bukhari","no":"6811",
     "en":"The greatest sins are associating partners with Allah, disobeying parents, murder, and false testimony.",
     "ru":"Величайшие грехи: многобожие, непослушание родителям, убийство и лжесвидетельство.",
     "tr":"En büyük günahlar: Allah'a ortak koşmak, anne babaya isyan, adam öldürmek ve yalan yere şahitlik.",
     "fr":"Les plus grands péchés sont: l'association à Allah, la désobéissance aux parents, le meurtre et le faux témoignage."},
    {"id":37,"narrator":"Abu Hurayrah","source":"Muslim","no":"2607",
     "en":"Whoever is not merciful to our young or respectful to our elders is not one of us.",
     "ru":"Не из нас тот, кто не милосерден к нашим младшим и не уважает наших старших.",
     "tr":"Küçüklerimize merhamet etmeyen, büyüklerimize saygı göstermeyen bizden değildir.",
     "fr":"N'est pas des nôtres celui qui n'est pas miséricordieux envers nos jeunes et respectueux envers nos anciens."},
    {"id":38,"narrator":"Aisha","source":"Bukhari","no":"3560",
     "en":"The Prophet never criticized food; if he liked it he ate it, and if he disliked it he left it.",
     "ru":"Пророк никогда не осуждал еду; если ему нравилось — ел, если нет — оставлял.",
     "tr":"Peygamber hiçbir zaman yemeği kötülemedi; beğendiyse yerdi, beğenmediyse bırakırdı.",
     "fr":"Le Prophète ne critiquait jamais la nourriture; s'il l'aimait il en mangeait, sinon il la laissait."},
    {"id":39,"narrator":"Abu Hurayrah","source":"Bukhari","no":"4",
     "en":"The first thing a person will be questioned about on the Day of Resurrection is prayer.",
     "ru":"Первое, о чём будет спрошен человек в День воскресения, — это молитва.",
     "tr":"Kıyamette kulun ilk sorgulanacağı şey namazdır.",
     "fr":"La première chose dont un homme sera interrogé le Jour de la Résurrection est la prière."},
    {"id":40,"narrator":"Anas ibn Malik","source":"Muslim","no":"2553",
     "en":"Cleanliness is half of faith; praise of Allah fills the scale.",
     "ru":"Чистота — половина веры; хвала Аллаху наполняет весы.",
     "tr":"Temizlik imanın yarısıdır; hamd teraziyi doldurur.",
     "fr":"La pureté est la moitié de la foi; la louange d'Allah remplit la balance."},
    {"id":41,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1903",
     "en":"Fast and you will be healthy.",
     "ru":"Поститесь — будете здоровы.",
     "tr":"Oruç tutun, sağlıklı olursunuz.",
     "fr":"Jeûnez et vous serez en bonne santé."},
    {"id":42,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"8",
     "en":"Islam is built on five pillars: testimony of faith, prayer, zakat, fasting, and pilgrimage.",
     "ru":"Ислам построен на пяти столпах: свидетельстве веры, молитве, закяте, посте и паломничестве.",
     "tr":"İslam beş temel üzerine bina edilmiştir: kelime-i şehadet, namaz, zekât, oruç ve hac.",
     "fr":"L'islam est bâti sur cinq piliers: la profession de foi, la prière, la zakat, le jeûne et le pèlerinage."},
    {"id":43,"narrator":"Abu Hurayrah","source":"Muslim","no":"2816",
     "en":"Whoever guides others to good will have a reward like those who do it.",
     "ru":"Кто указывает другим на благое, получит такую же награду, как и совершившие его.",
     "tr":"Hayra delalet eden, onu yapan gibi sevap alır.",
     "fr":"Celui qui guide les autres vers le bien aura une récompense semblable à celle de ceux qui le font."},
    {"id":44,"narrator":"Aisha","source":"Bukhari","no":"6130",
     "en":"The best charity is what is given when you are healthy and hopeful.",
     "ru":"Лучшая милостыня — та, что подаётся в здравии и с надеждой.",
     "tr":"En faziletli sadaka, sağlıklıyken ve ümit içindeyken verilen sadakadır.",
     "fr":"La meilleure aumône est celle donnée quand on est en bonne santé et plein d'espoir."},
    {"id":45,"narrator":"Abu Hurayrah","source":"Tirmidhi","no":"2004",
     "en":"Kindness is never found in something but it adorns it.",
     "ru":"Мягкость украшает всё, в чём она есть.",
     "tr":"Yumuşaklık, içinde bulunduğu her şeyi güzelleştirir.",
     "fr":"La douceur n'est jamais dans quelque chose sans l'embellir."},
    {"id":46,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2310",
     "en":"Whoever believes in Allah and the Last Day should not harm his neighbor.",
     "ru":"Кто верует в Аллаха и Судный день, пусть не причиняет вреда своему соседу.",
     "tr":"Allah'a ve ahiret gününe iman eden komşusuna eziyet etmesin.",
     "fr":"Que celui qui croit en Allah et au Jour dernier ne nuise pas à son voisin."},
    {"id":47,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6010",
     "en":"The sign of a hypocrite has three traits: when he speaks he lies, when he promises he breaks it, when trusted he betrays.",
     "ru":"Признак лицемера три: когда говорит — лжёт, когда обещает — нарушает, когда доверяют — предаёт.",
     "tr":"Münafığın alameti üçtür: konuşursa yalan söyler, söz verirse döner, emanet verilirse ihanet eder.",
     "fr":"Le signe du hypocrite a trois traits: quand il parle il ment, quand il promet il ne tient pas, quand on lui fait confiance il trahit."},
    {"id":48,"narrator":"Abu Dharr","source":"Muslim","no":"2577",
     "en":"Fear Allah wherever you are, follow a bad deed with a good deed to wipe it out.",
     "ru":"Бойся Аллаха везде; вслед за плохим делом соверши доброе, чтобы оно стёрло его.",
     "tr":"Nerede olursan ol Allah'tan kork; kötü amelin ardından iyilik yap ki onu silsin.",
     "fr":"Crains Allah où que tu sois; fais suivre une mauvaise action d'une bonne pour l'effacer."},
    {"id":49,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2446",
     "en":"A Muslim is the one from whose tongue and hand other Muslims are safe.",
     "ru":"Мусульманин — тот, от чьего языка и руки в безопасности другие мусульмане.",
     "tr":"Müslüman, dilinden ve elinden diğer Müslümanların güvende olduğu kişidir.",
     "fr":"Le musulman est celui dont les autres musulmans sont à l'abri de sa langue et de sa main."},
    {"id":50,"narrator":"Abdullah ibn Amr","source":"Bukhari","no":"6065",
     "en":"Do not envy one another, do not hate one another, and be brothers.",
     "ru":"Не завидуйте друг другу, не ненавидьте друг друга и будьте братьями.",
     "tr":"Birbirinize haset etmeyin, birbirinize kin gütmeyin ve kardeş olun.",
     "fr":"Ne vous enviez pas les uns les autres, ne vous haïssez pas et soyez frères."},
    {"id":51,"narrator":"Abu Hurayrah","source":"Tirmidhi","no":"2380",
     "en":"The remembrance of Allah is the best of deeds.",
     "ru":"Поминание Аллаха — лучшее из деяний.",
     "tr":"Allah'ı zikretmek amellerin en hayırlısıdır.",
     "fr":"Le souvenir d'Allah est le meilleur des actes."},
    {"id":52,"narrator":"Uthman ibn Affan","source":"Bukhari","no":"5027",
     "en":"The one who recites the Quran proficiently will be with the noble, obedient angels.",
     "ru":"Тот, кто читает Коран и хорошо владеет им, будет вместе с благородными праведными посланцами.",
     "tr":"Kur'an'ı iyi okuyan, şerefli ve itaatkâr meleklerle beraberdir.",
     "fr":"Celui qui récite le Coran avec maîtrise sera avec les nobles anges obéissants."},
    {"id":53,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2707",
     "en":"The most complete of the believers in faith are those with the best character.",
     "ru":"Самый совершенный по вере верующий — тот, у кого лучший нрав.",
     "tr":"Müminlerin iman bakımından en kâmili, ahlakı en güzel olandır.",
     "fr":"Le croyant le plus accompli dans la foi est celui qui a le meilleur caractère."},
    {"id":54,"narrator":"Abdullah ibn Umar","source":"Tirmidhi","no":"2416",
     "en":"Be in this world as though you were a stranger or a wayfarer.",
     "ru":"Будь в этом мире как странник или путник.",
     "tr":"Bu dünyada sanki bir yabancı veya yolcu gibi ol.",
     "fr":"Sois dans ce monde comme un étranger ou un voyageur de passage."},
    {"id":55,"narrator":"Abu Hurayrah","source":"Muslim","no":"2699",
     "en":"Allah did not send down any disease but He also sent down the cure.",
     "ru":"Аллах не ниспослал ни одну болезнь, не ниспослав для неё и лекарство.",
     "tr":"Allah her hastalık için bir deva indirmiştir.",
     "fr":"Allah n'a envoyé aucune maladie sans en envoyer aussi le remède."},
    {"id":56,"narrator":"Anas ibn Malik","source":"Bukhari","no":"5678",
     "en":"There is a cure in three things: a drink of honey, cupping, and cauterization; but I forbid my nation from cauterization.",
     "ru":"Исцеление в трёх вещах: в питье мёда, в кровопускании и прижигании; но прижигание я запрещаю своей общине.",
     "tr":"Şifа üç şeydedir: bal içmek, hacamat ve dağlama; ancak dağlamayı ümmetim için yasaklarım.",
     "fr":"La guérison est en trois choses: boire du miel, la saignée et la cautérisation; mais j'interdis la cautérisation à ma communauté."},
    {"id":57,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6491",
     "en":"Two words are light on the tongue, heavy on the scale, beloved to the Most Merciful: Glory be to Allah the Almighty.",
     "ru":"Два слова лёгкие на языке, тяжёлые на весах, любимые Милостивым: Слава Аллаху Великому.",
     "tr":"Dilde hafif, mizanda ağır, Rahman'a sevimli iki kelime: Sübhanallahilazim.",
     "fr":"Deux mots légers sur la langue, lourds dans la balance, chers au Très Miséricordieux: Gloire à Allah le Puissant."},
    {"id":58,"narrator":"Abu Hurayrah","source":"Muslim","no":"223",
     "en":"Whoever builds a mosque for the sake of Allah, Allah will build for him a house in Paradise.",
     "ru":"Тот, кто построит мечеть ради Аллаха, Аллах построит для него дом в раю.",
     "tr":"Allah rızası için cami inşa edene Allah cennette ev inşa eder.",
     "fr":"Quiconque construit une mosquée pour Allah, Allah lui construira une maison au paradis."},
    {"id":59,"narrator":"Abdullah ibn Abbas","source":"Bukhari","no":"6411",
     "en":"Take advantage of five before five: your youth before your old age, health before sickness, wealth before poverty, free time before busyness, and life before death.",
     "ru":"Пользуйся пятью до пяти: молодостью до старости, здоровьем до болезни, богатством до бедности, свободным временем до занятости, и жизнью до смерти.",
     "tr":"Beşi, beşten önce ganimet bil: gençliği ihtiyarlıktan, sağlığı hastalıktan, zenginliği fakirlikten, boş vakti meşguliyetten, hayatı ölümden önce.",
     "fr":"Profite de cinq choses avant cinq: ta jeunesse avant ta vieillesse, ta santé avant ta maladie, ta richesse avant la pauvreté, ton temps libre avant l'occupation, et ta vie avant ta mort."},
    {"id":60,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1358",
     "en":"Do not speak ill of the dead, for they have reached what they sent forth.",
     "ru":"Не поносите покойников, ибо они уже пришли к тому, что совершили.",
     "tr":"Ölülerinize sövmeyin, zira onlar yaptıklarının karşılığına ulaştılar.",
     "fr":"Ne dites pas du mal des morts, car ils ont atteint ce qu'ils ont envoyé devant eux."},
    {"id":61,"narrator":"Abu Hurayrah","source":"Muslim","no":"2564",
     "en":"Allah does not look at your bodies and appearances, but He looks at your hearts and deeds.",
     "ru":"Поистине, Аллах не смотрит на ваши тела и облик, но смотрит на ваши сердца и дела.",
     "tr":"Allah bedenlerinize ve görünüşünüze bakmaz; kalplerinize ve amellerinize bakar.",
     "fr":"Allah ne regarde pas vos corps ni vos apparences, mais Il regarde vos cœurs et vos actes."},
    {"id":62,"narrator":"Abu Hurayrah","source":"Bukhari","no":"5988",
     "en":"Maintain ties of kinship, even if others cut them.",
     "ru":"Кто уверовал в Аллаха и последний день, пусть поддерживает родственные связи.",
     "tr":"Allah'a ve ahiret gününe iman eden sıla-i rahmi gözetsin.",
     "fr":"Que celui qui croit en Allah et au Jour dernier maintienne les liens de parenté."},
    {"id":63,"narrator":"Abu Hurayrah","source":"Tirmidhi","no":"2307",
     "en":"Remember death often, for it destroys pleasures.",
     "ru":"Поминайте смерть почаще, ибо она разрушает наслаждения.",
     "tr":"Lezzetleri yok eden ölümü çokça hatırlayın.",
     "fr":"Souvenez-vous souvent de la mort, car elle détruit les plaisirs."},
    {"id":64,"narrator":"Abu Hurayrah","source":"Bukhari","no":"5090",
     "en":"The best of your days is Friday.",
     "ru":"Лучшее из ваших дней — пятница.",
     "tr":"Günlerin en hayırlısı Cuma günüdür.",
     "fr":"Le meilleur de vos jours est le vendredi."},
    {"id":65,"narrator":"Abu Hurayrah","source":"Muslim","no":"2061",
     "en":"Avoid that which makes you doubt and stick to that which does not make you doubt.",
     "ru":"Избегай того, что тебя смущает, и делай то, что тебя не смущает.",
     "tr":"Seni şüpheye düşüreni bırak, şüpheye düşürmeyene yönel.",
     "fr":"Évite ce qui te fait douter et tiens-toi à ce qui ne te fait pas douter."},
    {"id":66,"narrator":"Aisha","source":"Muslim","no":"2127",
     "en":"Allah loves that when one of you does a deed, he does it with excellence.",
     "ru":"Поистине, Аллах любит, когда кто-то из вас делает дело наилучшим образом.",
     "tr":"Allah, birinizin bir iş yaptığında onu güzel yapmasını sever.",
     "fr":"Allah aime que lorsque l'un de vous fait une action, il la fasse avec excellence."},
    {"id":67,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6502",
     "en":"Allah the Almighty said: I am as My servant thinks of Me.",
     "ru":"Аллах Всевышний сказал: Я таков, каким считает Меня Мой раб.",
     "tr":"Yüce Allah şöyle buyurdu: Ben kulumun beni zannettiği gibiyim.",
     "fr":"Allah le Très-Haut a dit: Je suis tel que Mon serviteur pense de Moi."},
    {"id":68,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6440",
     "en":"Fulfilling a promise is a sign of faith.",
     "ru":"Выполнение обязательств — из признаков веры.",
     "tr":"Sözünde durmak imandan bir alâmettir.",
     "fr":"Tenir ses promesses est un signe de foi."},
    {"id":69,"narrator":"Abu Hurayrah","source":"Bukhari","no":"660",
     "en":"The most burdensome prayers for the hypocrites are the Isha and Fajr prayers.",
     "ru":"Самая тяжкая молитва для лицемеров — вечерняя и утренняя.",
     "tr":"Münafıklara en ağır gelen namaz yatsı ve sabah namazıdır.",
     "fr":"Les prières les plus lourdes pour les hypocrites sont la prière du soir et celle de l'aube."},
    {"id":70,"narrator":"Abdullah ibn Amr","source":"Abu Dawud","no":"4800",
     "en":"The most beloved of people to Allah are those who are most beneficial to people.",
     "ru":"Самый любимый Аллахом человек — тот, кто приносит наибольшую пользу людям.",
     "tr":"Allah'a en sevimli insan, insanlara en çok faydalı olandır.",
     "fr":"Les personnes les plus aimées d'Allah sont celles qui sont les plus utiles aux gens."},
    {"id":71,"narrator":"Abu Hurayrah","source":"Muslim","no":"2564",
     "en":"Do not conceal the faults of a Muslim brother; Allah will conceal your faults on the Day of Judgment.",
     "ru":"Тот, кто скрывает изъяны мусульманина, Аллах скроет его изъяны в Судный день.",
     "tr":"Bir Müslümanın ayıbını örten kimsenin ayıbını Allah kıyamette örter.",
     "fr":"Quiconque cache les défauts d'un frère musulman, Allah cachera ses défauts le Jour du Jugement."},
    {"id":72,"narrator":"Anas ibn Malik","source":"Tirmidhi","no":"2151",
     "en":"Paradise is surrounded by hardships and Hell is surrounded by desires.",
     "ru":"Рай окружён трудностями, а ад — страстями.",
     "tr":"Cennet güçlüklerle, cehennem ise şehvetlerle çevrilidir.",
     "fr":"Le paradis est entouré de difficultés et l'enfer est entouré de désirs."},
    {"id":73,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6491",
     "en":"Allah records good and bad deeds; whoever intended to do good and did it gets ten rewards.",
     "ru":"Поистине, Аллах записывает добрые и злые дела; кто намеревался сделать доброе и сделал — получит десятикратную награду.",
     "tr":"Allah iyi ve kötü amelleri yazar; iyilik yapmaya niyet edip yapana on sevap vardır.",
     "fr":"Allah enregistre les bonnes et mauvaises actions; celui qui avait l'intention de faire le bien et l'a fait reçoit dix récompenses."},
    {"id":74,"narrator":"Abu Hurayrah","source":"Muslim","no":"223",
     "en":"Subhanallah fills the scales.",
     "ru":"Слово «субханаллах» наполняет весы.",
     "tr":"Sübhanallah mizanı doldurur.",
     "fr":"Subhanallah remplit la balance."},
    {"id":75,"narrator":"Abu Umamah","source":"Tirmidhi","no":"2910",
     "en":"Whoever recites Ayat al-Kursi after every prayer will enter Paradise.",
     "ru":"Кто читает «аятуль-курси» после каждой молитвы, войдёт в рай.",
     "tr":"Her namazın ardından Ayetel Kürsî'yi okuyan cennete girer.",
     "fr":"Celui qui récite l'Ayat al-Kursi après chaque prière entrera au paradis."},
    {"id":76,"narrator":"Abdullah ibn Masud","source":"Tirmidhi","no":"3383",
     "en":"The best remembrance is La ilaha illallah, and the best supplication is Alhamdulillah.",
     "ru":"Наилучшее поминание — «ла иляха илляллах», наилучшая молитва — «альхамдулиллях».",
     "tr":"En hayırlı zikir 'Lâ ilâhe illallah', en hayırlı dua 'Elhamdülillah'tır.",
     "fr":"Le meilleur souvenir est La ilaha illallah, et la meilleure supplication est Alhamdulillah."},
    {"id":77,"narrator":"Malik ibn Anas","source":"Muwatta","no":"1661",
     "en":"Hold fast to the Quran and Sunnah and you will never go astray.",
     "ru":"Держитесь за Коран и Сунну — не заблудитесь.",
     "tr":"Kur'an'a ve Sünnete sarılın, asla sapmazsınız.",
     "fr":"Tenez-vous fermement au Coran et à la Sunnah et vous ne vous égarerez jamais."},
    {"id":78,"narrator":"Ibn Abbas","source":"Ibn Majah","no":"2340",
     "en":"Do not harm and do not be harmed.",
     "ru":"Не причиняй вреда и не получай вреда.",
     "tr":"Ne zarar ver ne de zarara uğra.",
     "fr":"Ne cause pas de tort et ne subis pas de tort."},
    {"id":79,"narrator":"Abu Said al-Khudri","source":"Tirmidhi","no":"2398",
     "en":"The greatest trial is that of the prophets, then the righteous, then those who follow them.",
     "ru":"Самое тяжёлое испытание — у пророков, затем у праведников, затем у следующих за ними.",
     "tr":"En ağır belâ peygamberlere, sonra sâlihlere, sonra sırasıyla diğerlerine gelir.",
     "fr":"L'épreuve la plus grande est celle des prophètes, puis des justes, puis de ceux qui les suivent."},
    {"id":80,"narrator":"Abu Hurayrah","source":"Muslim","no":"2816",
     "en":"The believer is a mirror to his fellow believer.",
     "ru":"Верующий — зеркало для верующего.",
     "tr":"Mü'min, mü'minin aynasıdır.",
     "fr":"Le croyant est un miroir pour son frère croyant."},
    {"id":81,"narrator":"Muadh ibn Jabal","source":"Bukhari","no":"128",
     "en":"Whoever dies knowing that there is no god but Allah will enter Paradise.",
     "ru":"Тот, кто умрёт, зная, что нет бога, кроме Аллаха, войдёт в рай.",
     "tr":"Lâ ilâhe illallah diyerek ölen cennete girer.",
     "fr":"Quiconque meurt en sachant qu'il n'y a pas de dieu sauf Allah entrera au paradis."},
    {"id":82,"narrator":"Abu Hurayrah","source":"Bukhari","no":"100",
     "en":"Allah does not take away knowledge by removing it from the hearts of people, but takes it away by the death of scholars.",
     "ru":"Поистине, Аллах не забирает знание, изымая его из сердец людей, но забирает знание вместе с учёными.",
     "tr":"Allah ilmi, insanların kalbinden söküp almaz; âlimlerin canını alarak ilmi alır.",
     "fr":"Allah ne retire pas la connaissance en l'arrachant des cœurs, mais en rappelant les savants."},
    {"id":83,"narrator":"Jabir ibn Abdullah","source":"Muslim","no":"867",
     "en":"The best of speech is the Book of Allah, and the best of guidance is the guidance of Muhammad.",
     "ru":"Лучшее из слов — слово Аллаха, лучшее из руководств — руководство Мухаммада.",
     "tr":"Sözün en hayırlısı Allah'ın Kitabı, yolun en hayırlısı Muhammed'in yoludur.",
     "fr":"Le meilleur des discours est le Livre d'Allah, et le meilleur des guides est le guide de Muhammad."},
    {"id":84,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1174",
     "en":"Attend the Friday prayer, for it is a command of Allah.",
     "ru":"Соблюдайте пятничную молитву, ибо она — повеление Аллаха.",
     "tr":"Cuma namazını kılın; zira o Allah'ın emridir.",
     "fr":"Assistez à la prière du vendredi, car c'est un commandement d'Allah."},
    {"id":85,"narrator":"Abu Said al-Khudri","source":"Muslim","no":"1017",
     "en":"If you have surplus food, share it with those who have none.",
     "ru":"Тот, у кого есть лишняя еда, пусть поделится с тем, у кого её нет.",
     "tr":"Fazla yiyeceği olan, yiyeceği olmayanla paylaşsın.",
     "fr":"Celui qui a de la nourriture en surplus, qu'il la partage avec celui qui n'en a pas."},
    {"id":86,"narrator":"Abu Hurayrah","source":"Tirmidhi","no":"2318",
     "en":"Verily, deeds are judged by their endings.",
     "ru":"Поистине, дела завершаются последним.",
     "tr":"Ameller, sonuçlarına göre değerlendirilir.",
     "fr":"En vérité, les actes sont jugés par leur conclusion."},
    {"id":87,"narrator":"Abu Dharr","source":"Ahmad","no":"21516",
     "en":"Whoever abandons the world for the sake of Allah, Allah will compensate him with better.",
     "ru":"Тот, кто покинет мирское ради Аллаха, Аллах возместит ему лучшим.",
     "tr":"Allah rızası için dünyayı terk edene Allah daha hayırlısını verir.",
     "fr":"Celui qui abandonne le monde pour l'amour d'Allah, Allah le compensera avec mieux."},
    {"id":88,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2363",
     "en":"Showing mercy to animals is also a form of charity.",
     "ru":"Милосердие к животным — тоже садака.",
     "tr":"Hayvanlara merhamet etmek de sadakadır.",
     "fr":"Faire preuve de miséricorde envers les animaux est aussi une aumône."},
    {"id":89,"narrator":"Aisha","source":"Muslim","no":"2593",
     "en":"Allah is gentle and loves gentleness in all things.",
     "ru":"Аллах добр и любит доброту во всём.",
     "tr":"Allah lütufkârdır ve her şeyde lütfu sever.",
     "fr":"Allah est doux et Il aime la douceur en toutes choses."},
    {"id":90,"narrator":"Ibn Abbas","source":"Tirmidhi","no":"3383",
     "en":"Verily, with hardship comes ease.",
     "ru":"Поистине, с трудностью приходит облегчение.",
     "tr":"Şüphesiz her güçlükle birlikte bir kolaylık vardır.",
     "fr":"En vérité, avec la difficulté vient la facilité."},
    {"id":91,"narrator":"Abu Hurayrah","source":"Muslim","no":"2674",
     "en":"Whoever calls to guidance will have a reward equal to those who follow him.",
     "ru":"Кто призывает к верному пути, получит такую же награду, что и следующие за ним.",
     "tr":"Doğru yola davet eden, ona uyanların sevabının benzerini alır.",
     "fr":"Celui qui appelle à la bonne direction aura une récompense égale à ceux qui le suivent."},
    {"id":92,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2227",
     "en":"The best of you are those who are best in repaying debts.",
     "ru":"Лучший из вас тот, кто лучше всех выплачивает долги.",
     "tr":"En hayırlınız, borcunu en güzel şekilde ödeyeninizdir.",
     "fr":"Le meilleur d'entre vous est celui qui rembourse le mieux ses dettes."},
    {"id":93,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6064",
     "en":"Do not cut off relations, do not turn away from one another, do not hate one another, and be servants of Allah as brothers.",
     "ru":"Не разрывайте отношений, не отворачивайтесь друг от друга, не ненавидьте друг друга и будьте рабами Аллаха братьями.",
     "tr":"Birbirinizle ilişkileri kesmeyin, birbirinizden yüz çevirmeyin, birbirinize kin gütmeyin ve Allah'ın kulları olarak kardeş olun.",
     "fr":"Ne rompez pas les relations, ne vous détournez pas les uns des autres, ne vous haïssez pas et soyez frères en tant que serviteurs d'Allah."},
    {"id":94,"narrator":"Abu Hurayrah","source":"Bukhari","no":"5974",
     "en":"He who believes in Allah and the Last Day should honor his guest.",
     "ru":"Кто верует в Аллаха и последний день, пусть чтит гостя.",
     "tr":"Allah'a ve ahiret gününe iman eden misafirine ikram etsin.",
     "fr":"Que celui qui croit en Allah et au Jour dernier honore son hôte."},
    {"id":95,"narrator":"Abu Hurayrah","source":"Bukhari","no":"3461",
     "en":"The Children of Israel were led by prophets; whenever a prophet died, another prophet succeeded him.",
     "ru":"Детьми Израиля управляли пророки; когда умирал один пророк, его сменял другой.",
     "tr":"İsrailoğulları, peygamberler tarafından yönetiliyordu; biri ölünce yerine başkası geçerdi.",
     "fr":"Les enfants d'Israël étaient gouvernés par des prophètes; quand un prophète mourait, un autre le remplaçait."},
    {"id":96,"narrator":"Abu Hurayrah","source":"Muslim","no":"2812",
     "en":"The strong believer is better and more beloved to Allah than the weak believer.",
     "ru":"Сильный верующий лучше и более любим Аллахом, чем слабый верующий.",
     "tr":"Güçlü mü'min, zayıf mü'minden hayırlı ve Allah'a daha sevimlidir.",
     "fr":"Le croyant fort est meilleur et plus aimé d'Allah que le croyant faible."},
    {"id":97,"narrator":"Aisha","source":"Bukhari","no":"3560",
     "en":"The Prophet was not indecent or obscene; he used to say that the best among you are those who are best to their wives.",
     "ru":"Пророк не был непристойным или грубым; он говорил, что лучшие из вас — те, кто лучше всех относится к своим жёнам.",
     "tr":"Peygamber kaba ve çirkin sözlü değildi; en hayırlınız eşine en iyi davananızdır derdi.",
     "fr":"Le Prophète n'était ni indécent ni grossier; il disait que le meilleur parmi vous est celui qui est le meilleur envers sa femme."},
    {"id":98,"narrator":"Abu Hurayrah","source":"Bukhari","no":"5185",
     "en":"Treat women well, for they were created from a rib.",
     "ru":"Обращайтесь с женщинами хорошо, ибо они созданы из ребра.",
     "tr":"Kadınlara iyi davranın; zira onlar kaburga kemiğinden yaratılmıştır.",
     "fr":"Traitez bien les femmes, car elles ont été créées d'une côte."},
    {"id":99,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1356",
     "en":"Every child is born in a state of fitrah (natural disposition).",
     "ru":"Каждый ребёнок рождается в состоянии фитра (естественной предрасположенности).",
     "tr":"Her çocuk fıtrat üzere doğar.",
     "fr":"Chaque enfant naît dans un état de fitrah (disposition naturelle)."},
    {"id":100,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"1386",
     "en":"The deceased is punished in his grave for the wailing of his family over him.",
     "ru":"Усопший подвергается наказанию в могиле из-за плача семьи по нему.",
     "tr":"Ölü, ailesinin ağlaması sebebiyle kabrinde azap görür.",
     "fr":"Le défunt est puni dans sa tombe à cause des lamentations de sa famille."},
    {"id":101,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2674",
     "en":"Whoever relieves a believer of a worldly grief, Allah will relieve him of a grief on the Day of Resurrection.",
     "ru":"Кто снимет с верующего мирскую скорбь, Аллах снимет с него скорбь в День воскресения.",
     "tr":"Bir mü'minin dünya kederini gideren kimsenin kıyamet gününün kederini Allah giderir.",
     "fr":"Celui qui soulage un croyant d'une peine mondaine, Allah le soulagera d'une peine au Jour de la Résurrection."},
    {"id":102,"narrator":"Anas ibn Malik","source":"Bukhari","no":"1358",
     "en":"Seek knowledge even if it is in China.",
     "ru":"Ищи знания, даже если они в Китае.",
     "tr":"İlmi Çin'de de olsa arayınız.",
     "fr":"Cherche la connaissance même si elle est en Chine."},
    {"id":103,"narrator":"Abu Hurayrah","source":"Muslim","no":"1631",
     "en":"When a man dies, his deeds come to an end except for three: a continuous charity, knowledge that is beneficial, or a righteous child who prays for him.",
     "ru":"Когда умирает человек, его дела прекращаются, кроме трёх: непрерывной садаки, полезных знаний или праведного ребёнка, молящегося за него.",
     "tr":"İnsan öldüğünde ameli üç şey dışında kesilir: sadaka-i câriye, faydalı ilim ve kendisine dua eden salih çocuk.",
     "fr":"Quand un homme meurt, ses actes s'arrêtent sauf trois: une charité continue, une connaissance bénéfique, ou un enfant pieux qui prie pour lui."},
    {"id":104,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2766",
     "en":"Avoid the seven destructive sins.",
     "ru":"Остерегайтесь семи губительных грехов.",
     "tr":"Yedi helak edici şeyden kaçının.",
     "fr":"Évitez les sept péchés destructeurs."},
    {"id":105,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2475",
     "en":"The Muslim has five duties toward his fellow Muslim: return his salams, visit him when he is sick, follow his funeral, accept his invitation, and say yarhamukallah when he sneezes.",
     "ru":"У мусульманина пять обязанностей перед мусульманином: отвечать на приветствие, навещать больного, провожать покойного, принимать приглашение и говорить «ярхамукаллах» при чихании.",
     "tr":"Müslümanın Müslüman üzerinde beş hakkı vardır: selâmını almak, hastasını ziyaret etmek, cenazesine katılmak, davetine icabet etmek, aksırınca yerhamukallah demek.",
     "fr":"Le musulman a cinq devoirs envers son frère musulman: répondre à son salut, lui rendre visite quand il est malade, suivre son convoi funèbre, accepter son invitation, et dire yarhamukallah quand il éternue."},
    {"id":106,"narrator":"Abdullah ibn Abbas","source":"Tirmidhi","no":"2516",
     "en":"Guard your duty to Allah and He will guard you.",
     "ru":"Оберегай (права) Аллаха — и Аллах будет оберегать тебя.",
     "tr":"Allah'ın hakkını gözet, Allah da seni gözetsin.",
     "fr":"Préserve les droits d'Allah et Il te préservera."},
    {"id":107,"narrator":"Abu Hurayrah","source":"Bukhari","no":"4837",
     "en":"The best prayer after the obligatory ones is the night prayer.",
     "ru":"Лучшая молитва после обязательных — ночная молитва.",
     "tr":"Farz namazlardan sonra en hayırlı namaz gece namazıdır.",
     "fr":"La meilleure prière après les obligatoires est la prière de nuit."},
    {"id":108,"narrator":"Abu Hurayrah","source":"Muslim","no":"2326",
     "en":"Do not say bad things about time, for Allah is time.",
     "ru":"Не ругайте время, ибо Аллах есть время.",
     "tr":"Zamana sövmeyin; zira Allah zamandır.",
     "fr":"Ne dites pas du mal du temps, car Allah est le temps."},
    {"id":109,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6015",
     "en":"Make things easy for people, not difficult, and give glad tidings, do not make them run away.",
     "ru":"Облегчайте людям, не затрудняйте, радуйте и не отпугивайте.",
     "tr":"İnsanlara kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin.",
     "fr":"Facilitez les choses aux gens, ne les compliquez pas; donnez de bonnes nouvelles, ne les faites pas fuir."},
    {"id":110,"narrator":"Abu Hurayrah","source":"Muslim","no":"47",
     "en":"Whoever sees an evil must change it with his hand; if he cannot, then with his tongue; if he cannot, then with his heart.",
     "ru":"Кто увидит зло, пусть изменит его рукой; если не может — словом; если не может — сердцем.",
     "tr":"Biriniz bir kötülük görürse eliyle değiştirsin; gücü yetmezse diliyle; gücü yetmezse kalbiyle.",
     "fr":"Quiconque voit un mal doit le changer avec sa main; s'il ne peut pas, alors avec sa langue; s'il ne peut pas, alors avec son cœur."},
    {"id":111,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6021",
     "en":"Beware of suspicion, for it is the most lying form of speech.",
     "ru":"Остерегайтесь дурных предположений, ибо дурное предположение — ложь.",
     "tr":"Zandan sakının; zira zan, sözün en yalanıdır.",
     "fr":"Méfiez-vous des suspicions, car c'est la forme de parole la plus mensongère."},
    {"id":112,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6133",
     "en":"The believer does not get stung from the same hole twice.",
     "ru":"Верующий не кусается дважды из одной норы.",
     "tr":"Mü'min aynı delikten iki kez sokulmaz.",
     "fr":"Le croyant ne se fait pas piquer deux fois par le même trou."},
    {"id":113,"narrator":"Abdullah ibn Masud","source":"Bukhari","no":"3282",
     "en":"Verily, truthfulness leads to righteousness, and righteousness leads to Paradise.",
     "ru":"Поистине, правдивость ведёт к праведности, а праведность ведёт в рай.",
     "tr":"Doğruluk iyiliğe, iyilik de cennete götürür.",
     "fr":"La vérité mène à la vertu, et la vertu mène au paradis."},
    {"id":114,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6094",
     "en":"Backbiting is to mention about your brother what he would dislike.",
     "ru":"Гыйба — это упомянуть о своём брате то, что ему неприятно.",
     "tr":"Gıybet, kardeşinin hoşlanmayacağı şeyi onun arkasından söylemektir.",
     "fr":"La médisance c'est mentionner à propos de ton frère ce qu'il n'aimerait pas."},
    {"id":115,"narrator":"Anas ibn Malik","source":"Bukhari","no":"2518",
     "en":"None of you has faith until I am more beloved to him than his children, his father, and all people.",
     "ru":"Никто из вас не уверует, пока я не стану ему дороже его детей, его отца и всех людей.",
     "tr":"Hiçbiriniz, çocuğundan, babasından ve tüm insanlardan beni daha çok sevmedikçe iman etmiş olmaz.",
     "fr":"Aucun de vous n'a la foi tant que je ne lui suis pas plus cher que ses enfants, son père et tous les gens."},
    {"id":116,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1397",
     "en":"I have been commanded to fight people until they say La ilaha illallah.",
     "ru":"Мне велено сражаться с людьми до тех пор, пока они не скажут «Ла иляха илляллах».",
     "tr":"Lâ ilâhe illallah deyinceye kadar insanlarla savaşmam emredildi.",
     "fr":"Il m'a été commandé de combattre les gens jusqu'à ce qu'ils disent La ilaha illallah."},
    {"id":117,"narrator":"Abu Hurayrah","source":"Muslim","no":"2676",
     "en":"Whoever conceals a Muslim's fault, Allah will conceal his fault in this world and the hereafter.",
     "ru":"Кто скроет изъян мусульманина, Аллах скроет его изъян в этом мире и в будущем.",
     "tr":"Bir Müslümanın ayıbını örten kimsenin ayıbını Allah dünyada ve ahirette örter.",
     "fr":"Quiconque cache le défaut d'un musulman, Allah cachera son défaut en ce monde et dans l'au-delà."},
    {"id":118,"narrator":"Anas ibn Malik","source":"Muslim","no":"194",
     "en":"Between a man and shirk and kufr is the abandonment of prayer.",
     "ru":"Между человеком и многобожием и неверием — оставление молитвы.",
     "tr":"Kişi ile şirk ve küfür arasındaki fark namazı terk etmektir.",
     "fr":"Entre un homme et le shirk et le kufr, il y a l'abandon de la prière."},
    {"id":119,"narrator":"Abu Hurayrah","source":"Bukhari","no":"7138",
     "en":"The best jihad is a word of justice before a tyrannical ruler.",
     "ru":"Лучший джихад — слово справедливости перед тираном.",
     "tr":"En faziletli cihad, zalim yöneticinin karşısında hak sözü söylemektir.",
     "fr":"Le meilleur jihad est une parole de justice devant un dirigeant tyrannique."},
    {"id":120,"narrator":"Abu Dharr","source":"Muslim","no":"2577",
     "en":"Do not belittle any good deed, even meeting your brother with a cheerful face.",
     "ru":"Не считай ни одно доброе дело незначительным, даже встречу брата с улыбкой.",
     "tr":"Hiçbir iyiliği küçümseme; kardeşine güler yüzle kavuşmak bile olsa.",
     "fr":"Ne méprise aucune bonne action, même rencontrer ton frère avec un visage souriant."},
    {"id":121,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"5199",
     "en":"The best of Islam is feeding others and greeting those you know and those you don't.",
     "ru":"Лучшее в исламе — кормить других и приветствовать тех, кого знаешь и кого не знаешь.",
     "tr":"İslam'ın en hayırlısı yemek yedirmek ve tanıdık tanımadık herkese selam vermektir.",
     "fr":"Le meilleur de l'islam c'est de nourrir les autres et de saluer ceux que tu connais et ceux que tu ne connais pas."},
    {"id":122,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6117",
     "en":"Whoever does not give thanks to people does not give thanks to Allah.",
     "ru":"Тот, кто не благодарит людей, не благодарит Аллаха.",
     "tr":"İnsanlara teşekkür etmeyen Allah'a da şükretmemiş olur.",
     "fr":"Celui qui n'exprime pas sa gratitude aux gens n'exprime pas sa gratitude à Allah."},
    {"id":123,"narrator":"Anas ibn Malik","source":"Bukhari","no":"5765",
     "en":"Make things easy; do not make things difficult. Give glad tidings and do not make people run away.",
     "ru":"Облегчайте, не затрудняйте; радуйте и не отпугивайте.",
     "tr":"Kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin.",
     "fr":"Facilitez les choses; ne les compliquez pas. Donnez de bonnes nouvelles et ne faites pas fuir les gens."},
    {"id":124,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6018",
     "en":"Prayer is a pillar of religion.",
     "ru":"Молитва — опора религии.",
     "tr":"Namaz dinin direğidir.",
     "fr":"La prière est le pilier de la religion."},
    {"id":125,"narrator":"Abdullah ibn Masud","source":"Muslim","no":"179",
     "en":"Remember Allah standing, sitting, and lying on your side.",
     "ru":"Поминайте Аллаха стоя, сидя и лёжа на боку.",
     "tr":"Allah'ı ayakta, otururken ve yanınız üzere yatarken zikredin.",
     "fr":"Souvenez-vous d'Allah debout, assis et couché sur le côté."},
    {"id":126,"narrator":"Abu Hurayrah","source":"Muslim","no":"2687",
     "en":"Whoever loves to meet Allah, Allah loves to meet him.",
     "ru":"Тот, кто любит встречу с Аллахом, Аллах любит встречу с ним.",
     "tr":"Allah'a kavuşmayı seven kimseyle Allah da kavuşmayı sever.",
     "fr":"Celui qui aime rencontrer Allah, Allah aime le rencontrer."},
    {"id":127,"narrator":"Ibn Umar","source":"Tirmidhi","no":"3537",
     "en":"Allah accepts the repentance of a servant as long as the death rattle has not yet begun.",
     "ru":"Поистине, Аллах принимает покаяние раба, пока не наступила агония.",
     "tr":"Allah, can boğaza gelmedikçe kulunun tövbesini kabul eder.",
     "fr":"Allah accepte le repentir d'un serviteur tant que le râle de la mort n'a pas encore commencé."},
    {"id":128,"narrator":"Abu Hurayrah","source":"Bukhari","no":"3331",
     "en":"The best among you in the pre-Islamic period of ignorance are the best in Islam, if they understand Islamic teachings.",
     "ru":"Лучшие из вас в период невежества — лучшие в исламе, если они познают ислам.",
     "tr":"Cahiliye döneminde en hayırlı olanlarınız İslam'ı kavrarlarsa İslam'da da en hayırlı olanlardır.",
     "fr":"Les meilleurs d'entre vous à l'époque de l'ignorance sont les meilleurs en islam, s'ils comprennent les enseignements islamiques."},
    {"id":129,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6010",
     "en":"Whoever loves for Allah and hates for Allah has perfected his faith.",
     "ru":"Кто любит ради Аллаха и ненавидит ради Аллаха, тот завершил свою веру.",
     "tr":"Allah için seven, Allah için buğzeden imanını tamamlamıştır.",
     "fr":"Celui qui aime pour Allah et hait pour Allah a perfectionné sa foi."},
    {"id":130,"narrator":"Abu Hurayrah","source":"Muslim","no":"2633",
     "en":"Do not sever family ties, do not harbor hatred, and do not spy on one another.",
     "ru":"Не разрывайте связи, не питайте ненависти и не шпионьте друг за другом.",
     "tr":"Bağları kesmeyin, kin beslemeyin ve birbirinizi gözetlemeyin.",
     "fr":"Ne rompez pas les liens familiaux, ne nourrissez pas de haine et ne vous espionnez pas les uns les autres."},
    {"id":131,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6477",
     "en":"The love of this world is the root of all evil.",
     "ru":"Любовь к этому миру — корень всякого зла.",
     "tr":"Dünya sevgisi her hatanın başıdır.",
     "fr":"L'amour de ce monde est la racine de tout mal."},
    {"id":132,"narrator":"Abdullah ibn Amr","source":"Abu Dawud","no":"2597",
     "en":"Whoever is killed defending his property is a martyr.",
     "ru":"Кто убит, защищая своё имущество, — мученик.",
     "tr":"Malını savunurken öldürülen şehittir.",
     "fr":"Celui qui est tué en défendant ses biens est un martyr."},
    {"id":133,"narrator":"Abu Hurayrah","source":"Muslim","no":"2999",
     "en":"Richness is not having many possessions but richness is being content with oneself.",
     "ru":"Богатство — не в обилии имущества; богатство — в богатстве души.",
     "tr":"Zenginlik mal çokluğundan değil, gönül zenginliğindedir.",
     "fr":"La richesse ne consiste pas à avoir beaucoup de possessions, mais la richesse est d'être satisfait de soi-même."},
    {"id":134,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6015",
     "en":"Whoever has three daughters and is patient with them will enter Paradise.",
     "ru":"Кто имеет трёх дочерей и терпеливо заботится о них, войдёт в рай.",
     "tr":"Kim üç kızı olur ve onlara sabırla bakarsa cennete girer.",
     "fr":"Quiconque a trois filles et est patient avec elles entrera au paradis."},
    {"id":135,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1374",
     "en":"When a person dies, the angels ask: What has he sent forth? And the people say: What has he left behind?",
     "ru":"Когда человек умирает, ангелы спрашивают: что он отправил вперёд? А люди говорят: что он оставил после себя?",
     "tr":"İnsan ölünce melekler 'Ne gönderdi?' diye sorar; halk ise 'Ne bıraktı?' der.",
     "fr":"Quand une personne meurt, les anges demandent: Qu'a-t-il envoyé devant lui? Et les gens disent: Qu'a-t-il laissé derrière lui?"},
    {"id":136,"narrator":"Abu Said al-Khudri","source":"Bukhari","no":"1376",
     "en":"Whoever fasts Ramadan with faith and expecting reward will have all his past sins forgiven.",
     "ru":"Кто постится в Рамадан с верой и надеждой на награду, тому простятся прошлые грехи.",
     "tr":"Kim iman ederek ve sevabını bekleyerek Ramazan orucunu tutarsa geçmiş günahları bağışlanır.",
     "fr":"Quiconque jeûne le Ramadan avec foi et en espérant la récompense aura tous ses péchés passés pardonnés."},
    {"id":137,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1901",
     "en":"Whoever stands in prayer during Laylat al-Qadr with faith and expecting reward will have all his past sins forgiven.",
     "ru":"Кто встаёт для молитвы в Ночь предопределения с верой и надеждой на награду, тому простятся прошлые грехи.",
     "tr":"Kim iman ederek ve sevabını bekleyerek Kadir Gecesi'ni ihya ederse geçmiş günahları bağışlanır.",
     "fr":"Quiconque prie durant la Nuit du Destin avec foi et en espérant la récompense aura tous ses péchés passés pardonnés."},
    {"id":138,"narrator":"Anas ibn Malik","source":"Muslim","no":"2553",
     "en":"The supplication of a fasting person is not rejected.",
     "ru":"Мольба постящегося не отвергается.",
     "tr":"Oruçlunun duası reddedilmez.",
     "fr":"La supplication d'une personne qui jeûne n'est pas rejetée."},
    {"id":139,"narrator":"Abu Hurayrah","source":"Bukhari","no":"7492",
     "en":"Allah laughs at two men: one who kills the other, then both of them enter Paradise.",
     "ru":"Аллах смеётся двум мужчинам: одному, который убил другого, затем оба вошли в рай.",
     "tr":"Allah iki kişiye güler: biri diğerini öldürür, sonra ikisi de cennete girer.",
     "fr":"Allah rit de deux hommes: l'un tue l'autre, puis tous deux entrent au paradis."},
    {"id":140,"narrator":"Abu Hurayrah","source":"Muslim","no":"2564",
     "en":"He is not a believer who eats his fill when his neighbor is hungry.",
     "ru":"Не верующий тот, кто ест досыта, тогда как его сосед рядом с ним голоден.",
     "tr":"Komşusu aç iken tok yatan kişi iman etmiş değildir.",
     "fr":"Il n'est pas croyant celui qui mange à sa faim quand son voisin est affamé."},
    {"id":141,"narrator":"Abdullah ibn Abbas","source":"Bukhari","no":"6412",
     "en":"The pen has been lifted from three: the sleeper until he wakes, the child until he matures, and the insane until he recovers.",
     "ru":"Перо поднято с трёх: со спящего до пробуждения, с ребёнка до взросления, с безумного до выздоровления.",
     "tr":"Kalem üçünden kaldırıldı: uyanana kadar uyuyandan, büluğa erene kadar çocuktan ve iyileşene kadar deliden.",
     "fr":"La plume a été levée pour trois: le dormeur jusqu'à son réveil, l'enfant jusqu'à sa maturité, et l'insensé jusqu'à sa guérison."},
    {"id":142,"narrator":"Abu Hurayrah","source":"Muslim","no":"1006",
     "en":"Give charity, for it will be a shield for you from the Fire.",
     "ru":"Подавайте милостыню, ибо она станет щитом для вас от Огня.",
     "tr":"Sadaka verin; zira o sizi Ateş'ten koruyacak bir kalkandır.",
     "fr":"Faites l'aumône, car elle sera un bouclier pour vous contre le Feu."},
    {"id":143,"narrator":"Anas ibn Malik","source":"Tirmidhi","no":"2517",
     "en":"Supplicate to Allah while being certain of being answered.",
     "ru":"Взывай к Аллаху с уверенностью в ответе.",
     "tr":"Allah'a icabet edeceğinden emin olarak dua edin.",
     "fr":"Suppliez Allah en étant certain d'être exaucé."},
    {"id":144,"narrator":"Abu Hurayrah","source":"Muslim","no":"2593",
     "en":"Verily Allah does not look to your appearances or your wealth but to your hearts and your actions.",
     "ru":"Поистине, Аллах смотрит не на вашу внешность и богатство, а на ваши сердца и поступки.",
     "tr":"Allah sizin dış görünüşünüze ve malınıza bakmaz; kalplerinize ve amellerinize bakar.",
     "fr":"Certes Allah ne regarde pas vos apparences ni vos richesses mais vos cœurs et vos actions."},
    {"id":145,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2767",
     "en":"The greatest sin is to associate partners with Allah, then to kill a soul, then to commit fornication.",
     "ru":"Величайший грех — придавать Аллаху сотоварищей, затем убивать человека, затем прелюбодействовать.",
     "tr":"En büyük günah Allah'a ortak koşmak, ardından adam öldürmek, ardından zina etmektir.",
     "fr":"Le plus grand péché est d'associer des partenaires à Allah, puis de tuer une âme, puis de commettre l'adultère."},
    {"id":146,"narrator":"Anas ibn Malik","source":"Bukhari","no":"13",
     "en":"There is a tree in Paradise called Tuba; a rider can travel under its shade for a hundred years without crossing it.",
     "ru":"В раю есть дерево под названием Туба; всадник может ехать под его тенью сто лет и не пересечь его.",
     "tr":"Cennette Tuba adında bir ağaç vardır; bir binici yüz yıl onun gölgesinde gitse bitiremez.",
     "fr":"Il y a un arbre au paradis appelé Tuba; un cavalier peut voyager sous son ombre pendant cent ans sans le traverser."},
    {"id":147,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6502",
     "en":"Allah is pleased with three things for you: that you worship Him alone, that you hold fast to His rope all together, and that you give sincere advice to whoever Allah puts in charge of your affairs.",
     "ru":"Аллах доволен тремя вещами: поклонением Ему одному, крепкому держанию за Его верёвку и искреннему совету тем, кого Аллах поставил управлять вашими делами.",
     "tr":"Allah üç şeyden razıdır: yalnız O'na ibadet etmenizden, hep birlikte O'nun ipine sarılmanızdan ve işlerinizi yönettiği kimselere nasihat etmenizden.",
     "fr":"Allah est satisfait de trois choses pour vous: que vous l'adoriez Lui seul, que vous teniez ferme à Sa corde tous ensemble, et que vous donniez de sincères conseils à ceux qu'Il a mis en charge de vos affaires."},
    {"id":148,"narrator":"Abu Hurayrah","source":"Muslim","no":"2818",
     "en":"Whoever recites Surah al-Kahf on Friday will have a light between him and the next Friday.",
     "ru":"Кто читает суру аль-Кахф в пятницу, у того будет свет между двумя пятницами.",
     "tr":"Kim Cuma günü Kehf Suresi'ni okursa iki Cuma arasında için nur aydınlatır.",
     "fr":"Quiconque récite la sourate al-Kahf le vendredi aura une lumière entre lui et le vendredi suivant."},
    {"id":149,"narrator":"Abu Hurayrah","source":"Bukhari","no":"3020",
     "en":"Observe prayer, give zakat, and obey your rulers, you will enter your Lord's Paradise.",
     "ru":"Совершайте молитву, выплачивайте закят и повинуйтесь своим правителям — войдёте в рай вашего Господа.",
     "tr":"Namazı kılın, zekâtı verin ve yöneticilerinize itaat edin; Rabbinizin cennetine girersiniz.",
     "fr":"Accomplissez la prière, donnez la zakat et obéissez à vos dirigeants, vous entrerez dans le paradis de votre Seigneur."},
    {"id":150,"narrator":"Anas ibn Malik","source":"Tirmidhi","no":"2006",
     "en":"The person who is constantly asked by others for advice has a good character.",
     "ru":"Человек с хорошим характером постоянно спрашивает совета у других.",
     "tr":"Sürekli danışılan kişi iyi ahlâklıdır.",
     "fr":"La personne qui est constamment consultée par les autres a un bon caractère."},
    {"id":151,"narrator":"Abu Hurayrah","source":"Bukhari","no":"7405",
     "en":"Allah created mercy in one hundred parts; He sent down one part to earth and kept ninety-nine.",
     "ru":"Аллах создал милосердие в ста частях; ниспослал одну часть на землю, а девяносто девять оставил.",
     "tr":"Allah merhameti yüz parça yarattı; bir parçasını yeryüzüne indirdi, doksan dokuzunu yanında sakladı.",
     "fr":"Allah a créé la miséricorde en cent parties; Il en a envoyé une partie sur terre et en a gardé quatre-vingt-dix-neuf."},
    {"id":152,"narrator":"Abdullah ibn Amr","source":"Bukhari","no":"6065",
     "en":"Whoever does not thank the small blessings will not be thankful for the big ones.",
     "ru":"Кто не благодарен за малое, не будет благодарен и за большое.",
     "tr":"Küçük nimetlere şükretmeyen, büyük nimetlere de şükretmez.",
     "fr":"Celui qui n'est pas reconnaissant pour les petites bénédictions ne le sera pas pour les grandes."},
    {"id":153,"narrator":"Abu Hurayrah","source":"Muslim","no":"1015",
     "en":"The upper hand is better than the lower hand. The upper hand is the one that gives, and the lower hand is the one that takes.",
     "ru":"Верхняя рука лучше нижней. Верхняя — дающая, нижняя — берущая.",
     "tr":"Üstteki el alttaki elden hayırlıdır. Üstteki el veren, alttaki el alan eldir.",
     "fr":"La main du dessus est meilleure que la main du dessous. La main du dessus est celle qui donne, et la main du dessous est celle qui reçoit."},
    {"id":154,"narrator":"Anas ibn Malik","source":"Bukhari","no":"2805",
     "en":"Patience at the time of a calamity is a virtue.",
     "ru":"Терпение во время несчастья — добродетель.",
     "tr":"Musibette sabır erdemdir.",
     "fr":"La patience face à la calamité est une vertu."},
    {"id":155,"narrator":"Abu Hurayrah","source":"Muslim","no":"2588",
     "en":"Whoever covers a Muslim's fault, Allah will cover his fault in this world and the next.",
     "ru":"Кто прикроет изъян мусульманина, Аллах прикроет его изъян в этом мире и будущем.",
     "tr":"Bir Müslümanın ayıbını kapatan kimsenin ayıbını Allah bu dünyada ve ahirette kapatır.",
     "fr":"Quiconque cache le défaut d'un musulman, Allah cachera son défaut en ce monde et dans l'au-delà."},
    {"id":156,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1423",
     "en":"Seven people will be shaded by Allah on the Day when there is no shade except His shade.",
     "ru":"Семь людей укроет Аллах в тени в тот день, когда не будет иной тени, кроме Его тени.",
     "tr":"Allah, kendi gölgesinden başka gölgenin olmadığı günde yedi kişiyi gölgelendirir.",
     "fr":"Sept personnes seront protégées par Allah le Jour où il n'y aura pas d'autre ombre que la Sienne."},
    {"id":157,"narrator":"Anas ibn Malik","source":"Muslim","no":"2577",
     "en":"Allah says: O son of Adam, so long as you call upon Me and ask of Me, I shall forgive you for what you have done.",
     "ru":"Аллах говорит: О сын Адама, пока ты взываешь ко Мне и просишь Меня, Я прощу тебе содеянное.",
     "tr":"Allah buyurur: Ey Âdemoğlu, sen bana dua ettikçe ve benden istedikçe seni bağışlarım.",
     "fr":"Allah dit: Ô fils d'Adam, tant que tu M'invoqueras et Me demanderas, Je te pardonnerai ce que tu as fait."},
    {"id":158,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6502",
     "en":"Whoever recites the last two verses of Surah al-Baqarah at night, they will suffice him.",
     "ru":"Кто читает последние два аята суры аль-Бакара ночью, ему этого будет достаточно.",
     "tr":"Kim gece Bakara Suresi'nin son iki ayetini okursa ona yeter.",
     "fr":"Quiconque récite les deux derniers versets de la sourate al-Baqara la nuit, ils lui suffiront."},
    {"id":159,"narrator":"Abu Hurayrah","source":"Muslim","no":"2702",
     "en":"The most perfect believers in terms of faith are those with the best character and who are most kind to their wives.",
     "ru":"Самый совершенный верующий по вере — тот, у кого лучший нрав и кто добрее всех к своей жене.",
     "tr":"Müminlerin en kâmil imanı olanları, en güzel ahlâklı ve eşine en iyi davananıdır.",
     "fr":"Les croyants les plus parfaits en matière de foi sont ceux qui ont le meilleur caractère et qui sont les plus gentils envers leurs épouses."},
    {"id":160,"narrator":"Abu Hurayrah","source":"Bukhari","no":"5641",
     "en":"There is no disease that Allah has created, except that He also has created its treatment.",
     "ru":"Нет болезни, которую Аллах сотворил, не сотворив для неё лечение.",
     "tr":"Allah yarattığı her hastalığın tedavisini de yaratmıştır.",
     "fr":"Il n'est pas de maladie qu'Allah a créée sans en avoir aussi créé le traitement."},
    {"id":161,"narrator":"Anas ibn Malik","source":"Bukhari","no":"2697",
     "en":"Help your brother when he is an oppressor by stopping him from oppression.",
     "ru":"Помоги своему брату, когда он угнетатель, — останови его от угнетения.",
     "tr":"Kardeşinin zalim olduğunda ona yardımını, onu zulümden alıkoymakla yap.",
     "fr":"Aide ton frère quand il est un oppresseur en l'empêchant de l'oppression."},
    {"id":162,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2989",
     "en":"Whoever believes in Allah and the Last Day should not harm his neighbor; treat women kindly.",
     "ru":"Кто верует в Аллаха и последний день, пусть не обижает соседа; обращайтесь с женщинами хорошо.",
     "tr":"Allah'a ve ahiret gününe iman eden komşusuna eziyet etmesin; kadınlara iyi davranın.",
     "fr":"Que celui qui croit en Allah et au Jour dernier ne nuise pas à son voisin; traitez bien les femmes."},
    {"id":163,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"1468",
     "en":"Zakat is obligatory on every Muslim who possesses the nisab for one year.",
     "ru":"Закят обязателен для каждого мусульманина, обладающего нисабом на протяжении года.",
     "tr":"Üzerinden bir yıl geçen nisap miktarı malı bulunan her Müslümana zekât farzdır.",
     "fr":"La zakat est obligatoire pour tout musulman possédant le nisab pendant une année."},
    {"id":164,"narrator":"Abu Hurayrah","source":"Muslim","no":"593",
     "en":"Pray the five daily prayers, fast Ramadan, give zakat, and perform Hajj.",
     "ru":"Совершайте пять ежедневных молитв, постите Рамадан, платите закят и совершайте хадж.",
     "tr":"Beş vakit namazı kılın, Ramazan orucunu tutun, zekâtı verin ve hacca gidin.",
     "fr":"Priez les cinq prières quotidiennes, jeûnez le Ramadan, donnez la zakat et effectuez le pèlerinage."},
    {"id":165,"narrator":"Anas ibn Malik","source":"Tirmidhi","no":"2344",
     "en":"The one who repents from sin is like one who has not sinned.",
     "ru":"Кающийся в грехе подобен тому, у кого нет греха.",
     "tr":"Günahtan tövbe eden, hiç günah işlememiş gibidir.",
     "fr":"Celui qui se repent d'un péché est comme celui qui n'a pas péché."},
    {"id":166,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6018",
     "en":"The best of charity is when you are healthy and hopeful of a long life.",
     "ru":"Лучшая садака — когда ты здоров и надеешься на долгую жизнь.",
     "tr":"En hayırlı sadaka sağlıklı ve uzun ömür ümidindeyken verilendir.",
     "fr":"La meilleure aumône est celle donnée quand vous êtes en bonne santé et espérez une longue vie."},
    {"id":167,"narrator":"Abdullah ibn Masud","source":"Bukhari","no":"3282",
     "en":"A man follows the religion of his friend; so each one should consider whom he makes his friend.",
     "ru":"Человек следует религии своего друга; поэтому пусть каждый смотрит, с кем он дружит.",
     "tr":"Kişi, dostunun dini üzeredir; herkes kiminle arkadaşlık ettiğine baksın.",
     "fr":"Un homme suit la religion de son ami; chacun devrait donc considérer qui il choisit comme ami."},
    {"id":168,"narrator":"Abu Hurayrah","source":"Muslim","no":"2699",
     "en":"Verily, your deeds are presented before Allah twice a week: on Monday and Thursday.",
     "ru":"Поистине, ваши деяния представляются Аллаху дважды в неделю: в понедельник и четверг.",
     "tr":"Ameller haftada iki kez Allah'a arz edilir: Pazartesi ve Perşembe.",
     "fr":"En vérité, vos actes sont présentés à Allah deux fois par semaine: le lundi et le jeudi."},
    {"id":169,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6477",
     "en":"Seeking knowledge is an obligation upon every Muslim.",
     "ru":"Поиск знаний обязателен для каждого мусульманина.",
     "tr":"İlim öğrenmek her Müslümana farzdır.",
     "fr":"La recherche de la connaissance est une obligation pour chaque musulman."},
    {"id":170,"narrator":"Abu Hurayrah","source":"Muslim","no":"2564",
     "en":"Do not envy each other, do not artificially inflate prices, do not hate each other.",
     "ru":"Не завидуйте друг другу, не взвинчивайте цены, не ненавидьте друг друга.",
     "tr":"Birbirinize haset etmeyin, fiyatları yapay şişirmeyin, birbirinize kin gütmeyin.",
     "fr":"Ne vous enviez pas les uns les autres, ne gonflez pas artificiellement les prix, ne vous haïssez pas."},
    {"id":171,"narrator":"Abdullah ibn Amr","source":"Bukhari","no":"4797",
     "en":"He who has no mercy will not be shown mercy.",
     "ru":"Тому, у кого нет милосердия, не будет оказано милосердие.",
     "tr":"Merhametsize merhamet edilmez.",
     "fr":"Celui qui n'a pas de miséricorde ne se verra pas accorder de miséricorde."},
    {"id":172,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2767",
     "en":"When Allah loves a person He calls Gabriel and tells him that He loves that person.",
     "ru":"Когда Аллах любит человека, Он зовёт Джибриля и говорит ему, что любит этого человека.",
     "tr":"Allah bir kulunu sevince Cebrail'i çağırır ve ona o kişiyi sevdiğini söyler.",
     "fr":"Quand Allah aime quelqu'un, Il appelle Gabriel et lui dit qu'Il aime cette personne."},
    {"id":173,"narrator":"Anas ibn Malik","source":"Muslim","no":"2577",
     "en":"Whoever prays the dawn prayer in congregation, then sits remembering Allah until sunrise, then prays two rak'ahs, it will be equal to a complete Hajj and Umrah.",
     "ru":"Кто совершает утреннюю молитву в джамаате, затем сидит и поминает Аллаха до восхода солнца, а затем совершает два ракаата, — это равно полному хаджу и умре.",
     "tr":"Kim cemaatla sabah namazı kılar, güneş doğana kadar Allah'ı zikrederek oturursa, ardından iki rekât namaz kılarsa bu tam bir hac ve umreye eşittir.",
     "fr":"Celui qui prie la prière de l'aube en congrégation, puis s'assoit à se souvenir d'Allah jusqu'au lever du soleil, puis prie deux rak'ahs, cela équivaudra à un Hajj et une Umrah complets."},
    {"id":174,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1862",
     "en":"Hajj is Arafah.",
     "ru":"Хадж — это Арафа.",
     "tr":"Hac, Arefe'dir.",
     "fr":"Le Hajj c'est Arafah."},
    {"id":175,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"1521",
     "en":"An accepted Hajj has no reward except Paradise.",
     "ru":"Принятый хадж не имеет награды, кроме рая.",
     "tr":"Mebrûr haccın karşılığı yalnızca cennettir.",
     "fr":"Un Hajj accepté n'a pas d'autre récompense que le paradis."},
    {"id":176,"narrator":"Abu Hurayrah","source":"Bukhari","no":"1773",
     "en":"Whoever performs Hajj and does not commit obscenity or wrongdoing will return as the day his mother bore him.",
     "ru":"Кто совершает хадж и не совершает непристойного и грехов, вернётся таким, каким его родила мать.",
     "tr":"Kim hacceder ve kötü söz söylemez ve günah işlemezse anasından doğduğu gibi döner.",
     "fr":"Quiconque accomplit le Hajj sans commettre d'obscénité ni de mauvaise action reviendra comme le jour où sa mère l'a mis au monde."},
    {"id":177,"narrator":"Anas ibn Malik","source":"Bukhari","no":"3",
     "en":"The best among you is the one who does not harm others with his tongue and his hands.",
     "ru":"Лучший из вас — тот, кто не причиняет вреда другим ни языком, ни руками.",
     "tr":"En hayırlınız dili ve eliyle insanlara zarar vermeyeninizdir.",
     "fr":"Le meilleur parmi vous est celui qui ne blesse pas les autres avec sa langue ni ses mains."},
    {"id":178,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6018",
     "en":"The deen is easy; no one makes the deen too hard except that it will overcome him.",
     "ru":"Дин лёгок; и никто не делает дин слишком трудным, кроме как терпит от этого поражение.",
     "tr":"Din kolaylaştırıcıdır; kim dinde aşırıya kaçarsa din onu yener.",
     "fr":"La religion est facile; personne ne rend la religion trop difficile sans qu'elle le surmonte."},
    {"id":179,"narrator":"Abdullah ibn Masud","source":"Bukhari","no":"3375",
     "en":"Whoever fears the night journey, he reaches his destination at dawn.",
     "ru":"Кто боится ночного путешествия, достигает пункта назначения на рассвете.",
     "tr":"Gece yolculuğundan korkan sabaha karşı hedefine ulaşır.",
     "fr":"Celui qui craint le voyage de nuit atteint sa destination à l'aube."},
    {"id":180,"narrator":"Abu Hurayrah","source":"Muslim","no":"2704",
     "en":"The dua of a Muslim for his absent brother is answered.",
     "ru":"Мольба мусульманина за отсутствующего брата принимается.",
     "tr":"Müslümanın gıyabında kardeşi için duası kabul edilir.",
     "fr":"La supplication d'un musulman pour son frère absent est exaucée."},
    {"id":181,"narrator":"Anas ibn Malik","source":"Tirmidhi","no":"3376",
     "en":"Supplication is the brain of worship.",
     "ru":"Дуа — мозг поклонения.",
     "tr":"Dua ibadetin beynidir.",
     "fr":"La supplication est le cerveau du culte."},
    {"id":182,"narrator":"Abu Hurayrah","source":"Bukhari","no":"6405",
     "en":"There are two blessings that many people are deceived about: health and free time.",
     "ru":"Два блага, которыми многие обмануты: здоровье и свободное время.",
     "tr":"Pek çok insanın aldandığı iki nimet: sağlık ve boş vakit.",
     "fr":"Il y a deux bénédictions dont beaucoup de gens sont trompés: la santé et le temps libre."},
    {"id":183,"narrator":"Abdullah ibn Umar","source":"Bukhari","no":"6416",
     "en":"Whoever wears silk in this life will not wear it in the Hereafter.",
     "ru":"Кто носит шёлк в этом мире, не наденет его в будущем.",
     "tr":"Bu dünyada ipek giyen ahirette giymez.",
     "fr":"Celui qui porte de la soie dans cette vie ne la portera pas dans l'Au-delà."},
    {"id":184,"narrator":"Abu Hurayrah","source":"Muslim","no":"1006",
     "en":"The best charity is that given when you are least wealthy.",
     "ru":"Лучшая садака — та, что дана, когда ты меньше всего богат.",
     "tr":"En hayırlı sadaka, en az zenginken verilendir.",
     "fr":"La meilleure aumône est celle donnée quand vous êtes le moins riche."},
    {"id":185,"narrator":"Anas ibn Malik","source":"Bukhari","no":"6018",
     "en":"The scholars are the heirs of the prophets.",
     "ru":"Учёные — наследники пророков.",
     "tr":"Âlimler peygamberlerin vârisleridir.",
     "fr":"Les savants sont les héritiers des prophètes."},
    {"id":186,"narrator":"Abu Hurayrah","source":"Muslim","no":"2564",
     "en":"The most virtuous jihad is to speak a word of truth before a tyrannical ruler.",
     "ru":"Наиболее добродетельный джихад — произнести слово истины перед тираном.",
     "tr":"En faziletli cihad, zalim yöneticinin karşısında hak sözü söylemektir.",
     "fr":"Le jihad le plus vertueux est de dire une parole de vérité devant un dirigeant tyrannique."},
    {"id":187,"narrator":"Abdullah ibn Abbas","source":"Bukhari","no":"1",
     "en":"The ink of the scholar is more sacred than the blood of the martyr.",
     "ru":"Чернила учёного священнее крови мученика.",
     "tr":"Âlimin mürekkebi, şehidin kanından kutsaldır.",
     "fr":"L'encre du savant est plus sacrée que le sang du martyr."},
    {"id":188,"narrator":"Abu Hurayrah","source":"Bukhari","no":"2989",
     "en":"Whoever Allah wants good for, He gives him understanding in the religion.",
     "ru":"Кому Аллах желает блага, тому Он даёт понимание в религии.",
     "tr":"Allah kimin için hayır isterse ona dinde anlayış verir.",
     "fr":"Pour celui à qui Allah veut du bien, Il lui donne la compréhension de la religion."},
    {"id":189,"narrator":"Abu Hurayrah","source":"Muslim","no":"2699",
     "en":"Verily, Allah is beautiful and He loves beauty.",
     "ru":"Поистине, Аллах прекрасен и любит красоту.",
     "tr":"Şüphesiz Allah güzeldir ve güzelliği sever.",
     "fr":"En vérité, Allah est beau et Il aime la beauté."},
]

def build(hadiths, lang_key, text_key):
    result = []
    for h in hadiths:
        result.append({
            "id": h["id"],
            lang_key: h[text_key],
            "narrator": h["narrator"],
            "source": h["source"],
            "reference_display": f"{h['source']} · No. {h['no']}"
        })
    return result

configs = [
    ("en", "text_en", "en"),
    ("ru", "text_ru", "ru"),
    ("tr", "text_tr", "tr"),
    ("fr", "text_fr", "fr"),
]

for (lang, key, text_key) in configs:
    data = build(HADITHS, key, text_key)
    path = f"src/namazym/data/hadith_{lang}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"hadiths": data}, f, ensure_ascii=False, indent=2)
    print(f"Saved: {path} ({len(data)} hadiths)")

print("All 189 hadith files done!")
