const fs = require('fs');
const path = require('path');
const {
  IOSConfig,
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} = require('@expo/config-plugins');

const APP_GROUP_ID = 'group.com.namazym.app';
const BRIDGE_GROUP_NAME = 'NamazymWidgetBridge';
const BRIDGE_FILES = ['NamazymWidgetBridge.swift', 'NamazymWidgetBridge.m'];
const WIDGET_TARGET_NAME = 'NamazymWidget';
const WIDGET_BUNDLE_ID = 'com.namazym.app.widget';
const WIDGET_TEMPLATE_DIR = 'namazym-widget-extension';
const WIDGET_SWIFT_FILES = [
  'NamazymWidgetBundle.swift',
  'NamazymWidget.swift',
  'NamazymWidgetProvider.swift',
  'NamazymWidgetSnapshot.swift',
  'NamazymWidgetViews.swift',
];
const WIDGET_GROUP_FILES = [
  ...WIDGET_SWIFT_FILES,
  'Info.plist',
  'NamazymWidget.entitlements',
  'Assets.xcassets',
];
const ANDROID_PACKAGE = 'com.namazym.app';
const ANDROID_WIDGET_TEMPLATE_DIR = 'namazym-android-widget';
const ANDROID_WIDGET_BRIDGE_TEMPLATE_DIR = 'namazym-android-widget-bridge';
const ANDROID_WIDGET_MANIFEST_MARKER = '<!-- @generated by withNamazymWidgetBridge: Android widgets -->';
const PODFILE_PATCH_MARKER = '# @generated by withNamazymWidgetBridge: Expo script path-space fixes';
const PODFILE_EXPO_SCRIPT_PHASE_HELPER = `${PODFILE_PATCH_MARKER}
def patch_expo_script_phases_for_spaces(installer)
  script_phase_fixes = [
    {
      :target => 'EXConstants',
      :phase => '[CP-User] Generate app.config for prebuilt Constants.manifest',
      :script => %q{bash -l -c '"$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"'}
    },
    {
      :target => 'EXUpdates',
      :phase => '[CP-User] Generate updates resources for expo-updates',
      :script => %q{bash -l -c '"$PODS_TARGET_SRCROOT/../scripts/create-updates-resources-ios.sh"'}
    }
  ]

  installer.pods_project.targets.each do |target|
    script_phase_fixes.each do |fix|
      next unless target.name == fix[:target]

      target.shell_script_build_phases.each do |phase|
        next unless phase.name == fix[:phase]

        phase.shell_script = fix[:script]
      end
    end
  end
end
`;

const ensureAppGroupEntitlement = (entitlements) => {
  const key = 'com.apple.security.application-groups';
  const existingGroups = Array.isArray(entitlements[key]) ? entitlements[key] : [];

  if (!existingGroups.includes(APP_GROUP_ID)) {
    entitlements[key] = [...existingGroups, APP_GROUP_ID];
  }

  return entitlements;
};

const copyBridgeTemplates = (projectRoot, platformRoot) => {
  const sourceDir = path.join(projectRoot, 'plugins', 'namazym-widget-bridge');
  const targetDir = path.join(platformRoot, BRIDGE_GROUP_NAME);

  fs.mkdirSync(targetDir, { recursive: true });

  for (const fileName of BRIDGE_FILES) {
    fs.copyFileSync(path.join(sourceDir, fileName), path.join(targetDir, fileName));
  }
};

const copyWidgetTemplates = (projectRoot, platformRoot) => {
  const sourceDir = path.join(projectRoot, 'plugins', WIDGET_TEMPLATE_DIR);
  const targetDir = path.join(platformRoot, WIDGET_TARGET_NAME);

  fs.mkdirSync(targetDir, { recursive: true });
  fs.cpSync(sourceDir, targetDir, { recursive: true, force: true });
};

const copyAndroidWidgetTemplates = (projectRoot, platformRoot) => {
  const packagePath = ANDROID_PACKAGE.replace(/\./g, path.sep);
  const mainRoot = path.join(platformRoot, 'app', 'src', 'main');
  const sourceWidgetDir = path.join(projectRoot, 'plugins', ANDROID_WIDGET_TEMPLATE_DIR);
  const sourceBridgeDir = path.join(projectRoot, 'plugins', ANDROID_WIDGET_BRIDGE_TEMPLATE_DIR);
  const targetWidgetDir = path.join(mainRoot, 'java', packagePath, 'widget');
  const targetBridgeDir = path.join(mainRoot, 'java', packagePath, 'widgetbridge');
  const targetResDir = path.join(mainRoot, 'res');

  fs.mkdirSync(targetWidgetDir, { recursive: true });
  fs.mkdirSync(targetBridgeDir, { recursive: true });
  fs.mkdirSync(targetResDir, { recursive: true });

  for (const fileName of fs.readdirSync(sourceWidgetDir)) {
    const sourcePath = path.join(sourceWidgetDir, fileName);
    const targetPath = path.join(targetWidgetDir, fileName);
    if (fs.statSync(sourcePath).isFile() && fileName.endsWith('.kt')) {
      fs.copyFileSync(sourcePath, targetPath);
    }
  }

  for (const fileName of fs.readdirSync(sourceBridgeDir)) {
    const sourcePath = path.join(sourceBridgeDir, fileName);
    const targetPath = path.join(targetBridgeDir, fileName);
    if (fs.statSync(sourcePath).isFile() && fileName.endsWith('.kt')) {
      fs.copyFileSync(sourcePath, targetPath);
    }
  }

  const sourceResDir = path.join(sourceWidgetDir, 'res');
  if (fs.existsSync(sourceResDir)) {
    fs.cpSync(sourceResDir, targetResDir, { recursive: true, force: true });
  }
};

const patchAndroidManifestForWidgets = (platformRoot) => {
  const manifestPath = path.join(platformRoot, 'app', 'src', 'main', 'AndroidManifest.xml');
  if (!fs.existsSync(manifestPath)) {
    return;
  }

  let manifest = fs.readFileSync(manifestPath, 'utf8');
  if (
    manifest.includes('NamazymSmallWidgetProvider')
    && manifest.includes('NamazymMediumWidgetProvider')
    && manifest.includes('NamazymLargeWidgetProvider')
  ) {
    return;
  }

  manifest = manifest.replace(
    new RegExp(`\\n\\s*${ANDROID_WIDGET_MANIFEST_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?\\n\\s*<!-- @generated end: Android widgets -->`, 'm'),
    '',
  );

  const receivers = `
    ${ANDROID_WIDGET_MANIFEST_MARKER}
    <receiver android:name=".widget.NamazymSmallWidgetProvider" android:exported="false">
      <intent-filter>
        <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
      </intent-filter>
      <meta-data android:name="android.appwidget.provider" android:resource="@xml/namazym_small_widget_info"/>
    </receiver>
    <receiver android:name=".widget.NamazymMediumWidgetProvider" android:exported="false">
      <intent-filter>
        <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
      </intent-filter>
      <meta-data android:name="android.appwidget.provider" android:resource="@xml/namazym_medium_widget_info"/>
    </receiver>
    <receiver android:name=".widget.NamazymLargeWidgetProvider" android:exported="false">
      <intent-filter>
        <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
      </intent-filter>
      <meta-data android:name="android.appwidget.provider" android:resource="@xml/namazym_large_widget_info"/>
    </receiver>
    <!-- @generated end: Android widgets -->`;

  if (!manifest.includes(ANDROID_WIDGET_MANIFEST_MARKER)) {
    manifest = manifest.replace(/\n\s*<\/application>/, `${receivers}\n  </application>`);
  }

  fs.writeFileSync(manifestPath, manifest);
};

const patchAndroidMainApplicationForBridge = (platformRoot) => {
  const mainApplicationPath = path.join(
    platformRoot,
    'app',
    'src',
    'main',
    'java',
    ...ANDROID_PACKAGE.split('.'),
    'MainApplication.kt',
  );
  if (!fs.existsSync(mainApplicationPath)) {
    return;
  }

  let contents = fs.readFileSync(mainApplicationPath, 'utf8');
  const importStatement = `import ${ANDROID_PACKAGE}.widgetbridge.NamazymWidgetBridgePackage`;
  if (!contents.includes(importStatement)) {
    contents = contents.replace(/package\s+[^\n]+\n/, (match) => `${match}\n${importStatement}\n`);
  }

  const packageStatement = 'add(NamazymWidgetBridgePackage())';
  if (!contents.includes(packageStatement)) {
    contents = contents.replace(
      /(\s*\/\/ Packages that cannot be autolinked yet can be added manually here, for example:\n\s*\/\/ add\(MyReactNativePackage\(\)\)\n)/,
      `$1              ${packageStatement}\n`,
    );
  }

  fs.writeFileSync(mainApplicationPath, contents);
};

const patchPodfileForExpoScriptPathSpaces = (platformRoot) => {
  const podfilePath = path.join(platformRoot, 'Podfile');
  if (!fs.existsSync(podfilePath)) {
    return;
  }

  let podfile = fs.readFileSync(podfilePath, 'utf8');
  podfile = podfile
    .replace(/# @generated by withNamazymWidgetBridge: EXConstants app\.config path-space fix\n[\s\S]*?^end\n\n/m, '')
    .replace(/\n\s*patch_exconstants_app_config_script_phase_for_spaces\(installer\)\n/, '\n');

  if (!podfile.includes(PODFILE_PATCH_MARKER)) {
    const targetBlockPattern = /^target\s+['"][^'"]+['"]\s+do/m;
    podfile = podfile.replace(targetBlockPattern, `${PODFILE_EXPO_SCRIPT_PHASE_HELPER}\n$&`);
  }

  const patchCall = '    patch_expo_script_phases_for_spaces(installer)';
  if (!podfile.includes(patchCall)) {
    const postInstallCallPattern = /(\n\s*react_native_post_install\([\s\S]*?\n\s*\)\n)/;
    podfile = podfile.replace(postInstallCallPattern, `$1${patchCall}\n`);
  }

  fs.writeFileSync(podfilePath, podfile);
};

const getMainTarget = (xcodeProject) => {
  const targets = xcodeProject.getFirstProject().firstProject.targets;
  const appTarget = targets.find((target) => {
    const nativeTarget = xcodeProject.pbxNativeTargetSection()[target.value];
    return nativeTarget?.productType === '"com.apple.product-type.application"';
  });

  return appTarget ?? xcodeProject.getFirstTarget();
};

const unquote = (value) => String(value ?? '').replace(/^"|"$/g, '');

const getTargetByName = (xcodeProject, targetName) => {
  const nativeTargets = xcodeProject.pbxNativeTargetSection();

  for (const [uuid, target] of Object.entries(nativeTargets)) {
    if (uuid.endsWith('_comment')) {
      continue;
    }

    if (unquote(target?.name) === targetName) {
      return { uuid, nativeTarget: target };
    }
  }

  return null;
};

const hasFileReference = (xcodeProject, filePath) => {
  const fileReferences = xcodeProject.hash.project.objects.PBXFileReference ?? {};

  return Object.values(fileReferences).some((fileReference) => {
    return fileReference?.path === filePath || fileReference?.path === `"${filePath}"`;
  });
};

const hasFileReferenceInGroup = (xcodeProject, group, fileName, groupName) => {
  const fileReferences = xcodeProject.hash.project.objects.PBXFileReference ?? {};
  const candidatePaths = new Set([fileName, `${groupName}/${fileName}`]);

  return (group.children ?? []).some((child) => {
    const fileReference = fileReferences[child.value];
    const name = unquote(fileReference?.name ?? child.comment);
    const filePath = unquote(fileReference?.path);
    return candidatePaths.has(name) || candidatePaths.has(filePath);
  });
};

const ensurePbxGroup = (xcodeProject, groupName) => {
  let group = xcodeProject.pbxGroupByName(groupName);
  if (!group) {
    group = xcodeProject.addPbxGroup([], groupName, groupName);
    const mainGroup = xcodeProject.getFirstProject().firstProject.mainGroup;
    xcodeProject.addToPbxGroup(group.uuid, mainGroup);
  }
  return group;
};

const ensureResourcesGroup = (xcodeProject) => {
  if (!xcodeProject.pbxGroupByName('Resources')) {
    const resourcesGroup = xcodeProject.addPbxGroup([], 'Resources', 'Resources');
    const mainGroup = xcodeProject.getFirstProject().firstProject.mainGroup;
    xcodeProject.addToPbxGroup(resourcesGroup.uuid, mainGroup);
  }
};

const getTargetBuildConfigurations = (xcodeProject, targetUuid) => {
  const target = xcodeProject.pbxNativeTargetSection()[targetUuid];
  const configurationList = xcodeProject.pbxXCConfigurationList()[target.buildConfigurationList];
  const buildConfigurations = xcodeProject.pbxXCBuildConfigurationSection();

  return (configurationList?.buildConfigurations ?? [])
    .map((item) => buildConfigurations[item.value])
    .filter(Boolean);
};

const findBuildPhase = (xcodeProject, targetUuid, phaseType, phaseName) => {
  const target = xcodeProject.pbxNativeTargetSection()[targetUuid];
  const phases = xcodeProject.hash.project.objects[phaseType] ?? {};

  for (const phaseRef of target?.buildPhases ?? []) {
    const phase = phases[phaseRef.value];
    if (phase?.isa !== phaseType) {
      continue;
    }

    if (!phaseName || unquote(phase.name ?? phaseRef.comment) === phaseName || phaseRef.comment === phaseName) {
      return { uuid: phaseRef.value, phase };
    }
  }

  return null;
};

const ensureBuildPhase = (xcodeProject, targetUuid, phaseType, phaseName, folderType) => {
  const existingPhase = findBuildPhase(xcodeProject, targetUuid, phaseType, phaseName);
  if (existingPhase) {
    return existingPhase;
  }

  const result = xcodeProject.addBuildPhase([], phaseType, phaseName, targetUuid, folderType);
  return { uuid: result.uuid, phase: result.buildPhase };
};

const addBridgeFilesToProject = (config, xcodeProject) => {
  const target = getMainTarget(xcodeProject);
  const targetUuid = target.uuid ?? target.value;
  const productName = IOSConfig.XcodeUtils.getProductName(xcodeProject);

  const bridgeGroup = ensurePbxGroup(xcodeProject, BRIDGE_GROUP_NAME);

  for (const fileName of BRIDGE_FILES) {
    if (hasFileReferenceInGroup(xcodeProject, bridgeGroup, fileName, BRIDGE_GROUP_NAME)) {
      continue;
    }

    xcodeProject.addSourceFile(fileName, { target: targetUuid }, bridgeGroup.uuid);
  }

  const buildConfigurations = xcodeProject.pbxXCBuildConfigurationSection();
  for (const buildConfiguration of Object.values(buildConfigurations)) {
    if (
      buildConfiguration?.buildSettings?.PRODUCT_NAME === `"${productName}"`
      || buildConfiguration?.buildSettings?.PRODUCT_NAME === productName
    ) {
      buildConfiguration.buildSettings.SWIFT_OBJC_BRIDGING_HEADER =
        `${productName}/${productName}-Bridging-Header.h`;
      buildConfiguration.buildSettings.SWIFT_VERSION =
        buildConfiguration.buildSettings.SWIFT_VERSION ?? '5.0';
    }
  }
};

const getBuildSettingFallback = (buildConfigurations, settingName, defaultValue) => {
  const configuration = buildConfigurations.find((item) => item?.buildSettings?.[settingName] != null);
  return configuration?.buildSettings?.[settingName] ?? defaultValue;
};

const configureWidgetBuildSettings = (config, xcodeProject, targetUuid, mainTargetUuid) => {
  const mainBuildConfigurations = getTargetBuildConfigurations(xcodeProject, mainTargetUuid);
  const mainBuildConfigurationsByName = new Map(
    mainBuildConfigurations.map((buildConfiguration) => [buildConfiguration.name, buildConfiguration]),
  );
  const fallbackMarketingVersion = config.version
    ?? getBuildSettingFallback(mainBuildConfigurations, 'MARKETING_VERSION', '1.0');
  const fallbackProjectVersion = config.ios?.buildNumber
    ?? getBuildSettingFallback(mainBuildConfigurations, 'CURRENT_PROJECT_VERSION', '1');

  for (const buildConfiguration of getTargetBuildConfigurations(xcodeProject, targetUuid)) {
    const mainBuildSettings = mainBuildConfigurationsByName.get(buildConfiguration.name)?.buildSettings ?? {};

    buildConfiguration.buildSettings = {
      ...buildConfiguration.buildSettings,
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: 'AccentColor',
      CODE_SIGN_ENTITLEMENTS: `${WIDGET_TARGET_NAME}/${WIDGET_TARGET_NAME}.entitlements`,
      CURRENT_PROJECT_VERSION: config.ios?.buildNumber ?? mainBuildSettings.CURRENT_PROJECT_VERSION ?? fallbackProjectVersion,
      GENERATE_INFOPLIST_FILE: 'NO',
      INFOPLIST_FILE: `${WIDGET_TARGET_NAME}/Info.plist`,
      IPHONEOS_DEPLOYMENT_TARGET: buildConfiguration.buildSettings.IPHONEOS_DEPLOYMENT_TARGET ?? '15.1',
      LD_RUNPATH_SEARCH_PATHS: '"$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"',
      MARKETING_VERSION: config.version ?? mainBuildSettings.MARKETING_VERSION ?? fallbackMarketingVersion,
      PRODUCT_BUNDLE_IDENTIFIER: WIDGET_BUNDLE_ID,
      PRODUCT_NAME: `"${WIDGET_TARGET_NAME}"`,
      SKIP_INSTALL: 'YES',
      SWIFT_VERSION: '5.0',
      TARGETED_DEVICE_FAMILY: '"1,2"',
    };
  }
};

const ensureTargetDependency = (xcodeProject, mainTargetUuid, widgetTargetUuid) => {
  const mainTarget = xcodeProject.pbxNativeTargetSection()[mainTargetUuid];
  const dependencySection = xcodeProject.hash.project.objects.PBXTargetDependency ?? {};

  const hasDependency = (mainTarget.dependencies ?? []).some((dependencyRef) => {
    return dependencySection[dependencyRef.value]?.target === widgetTargetUuid;
  });

  if (!hasDependency) {
    xcodeProject.addTargetDependency(mainTargetUuid, [widgetTargetUuid]);
  }
};

const isWidgetProductFileReference = (fileReference) => {
  const name = unquote(fileReference?.name);
  const path = unquote(fileReference?.path);
  return name === `${WIDGET_TARGET_NAME}.appex` || path === `${WIDGET_TARGET_NAME}.appex`;
};

const isWidgetProductBuildFile = (xcodeProject, buildFile, productReference) => {
  if (!buildFile || buildFile.isa !== 'PBXBuildFile') {
    return false;
  }

  if (buildFile.fileRef === productReference) {
    return true;
  }

  const fileReference = xcodeProject.hash.project.objects.PBXFileReference?.[buildFile.fileRef];
  return isWidgetProductFileReference(fileReference) || unquote(buildFile.fileRef_comment) === `${WIDGET_TARGET_NAME}.appex`;
};

const isAppExtensionCopyPhase = (phase, phaseRef) => {
  if (!phase || phase.isa !== 'PBXCopyFilesBuildPhase') {
    return false;
  }

  const phaseName = unquote(phase.name ?? phaseRef?.comment);
  return Number(phase.dstSubfolderSpec) === 13 || phaseName === 'Embed App Extensions';
};

const getAppExtensionCopyPhases = (xcodeProject, mainTargetUuid) => {
  const mainTarget = xcodeProject.pbxNativeTargetSection()[mainTargetUuid];
  const phases = xcodeProject.hash.project.objects.PBXCopyFilesBuildPhase ?? {};

  return (mainTarget?.buildPhases ?? [])
    .map((phaseRef) => ({
      uuid: phaseRef.value,
      phaseRef,
      phase: phases[phaseRef.value],
    }))
    .filter(({ phase, phaseRef }) => isAppExtensionCopyPhase(phase, phaseRef));
};

const findWidgetEmbedPhase = (xcodeProject, mainTargetUuid, productReference) => {
  const buildFiles = xcodeProject.pbxBuildFileSection();
  const extensionPhases = getAppExtensionCopyPhases(xcodeProject, mainTargetUuid);

  return extensionPhases.find(({ phase }) => {
    return (phase.files ?? []).some((fileRef) => {
      return isWidgetProductBuildFile(xcodeProject, buildFiles[fileRef.value], productReference);
    });
  }) ?? extensionPhases.find(({ phase }) => {
    return unquote(phase.name) === 'Embed App Extensions';
  }) ?? extensionPhases[0] ?? null;
};

const removeDuplicateWidgetEmbedPhases = (xcodeProject, mainTargetUuid, canonicalPhaseUuid, productReference) => {
  const mainTarget = xcodeProject.pbxNativeTargetSection()[mainTargetUuid];
  const copyPhases = xcodeProject.hash.project.objects.PBXCopyFilesBuildPhase ?? {};
  const buildFiles = xcodeProject.pbxBuildFileSection();
  const canonicalPhase = copyPhases[canonicalPhaseUuid];
  const canonicalFiles = canonicalPhase.files ?? [];
  canonicalPhase.files = canonicalFiles;

  const canonicalFileValues = new Set(canonicalFiles.map((fileRef) => fileRef.value));
  const widgetBuildFileValues = new Set();

  for (const phaseRef of mainTarget.buildPhases ?? []) {
    const phase = copyPhases[phaseRef.value];
    if (!isAppExtensionCopyPhase(phase, phaseRef)) {
      continue;
    }

    const retainedFiles = [];
    for (const fileRef of phase.files ?? []) {
      const buildFile = buildFiles[fileRef.value];
      if (isWidgetProductBuildFile(xcodeProject, buildFile, productReference)) {
        widgetBuildFileValues.add(fileRef.value);
        continue;
      }

      retainedFiles.push(fileRef);
      if (phaseRef.value !== canonicalPhaseUuid && !canonicalFileValues.has(fileRef.value)) {
        canonicalPhase.files.push(fileRef);
        canonicalFileValues.add(fileRef.value);
      }
    }

    phase.files = phaseRef.value === canonicalPhaseUuid ? phase.files : retainedFiles;
  }

  mainTarget.buildPhases = (mainTarget.buildPhases ?? []).filter((phaseRef) => {
    if (phaseRef.value === canonicalPhaseUuid) {
      return true;
    }

    const phase = copyPhases[phaseRef.value];
    if (!isAppExtensionCopyPhase(phase, phaseRef)) {
      return true;
    }

    if ((phase.files ?? []).length > 0) {
      return true;
    }

    delete copyPhases[phaseRef.value];
    delete copyPhases[`${phaseRef.value}_comment`];
    return false;
  });

  return [...widgetBuildFileValues];
};

const ensureWidgetEmbeddedInApp = (xcodeProject, mainTargetUuid, widgetTargetUuid) => {
  const widgetTarget = xcodeProject.pbxNativeTargetSection()[widgetTargetUuid];
  const productReference = widgetTarget.productReference;
  const buildFiles = xcodeProject.pbxBuildFileSection();
  const existingPhase = findWidgetEmbedPhase(xcodeProject, mainTargetUuid, productReference);
  const embedPhaseRef = existingPhase ?? ensureBuildPhase(
    xcodeProject,
    mainTargetUuid,
    'PBXCopyFilesBuildPhase',
    'Embed App Extensions',
    'app_extension',
  );
  const embedPhase = embedPhaseRef.phase;

  embedPhase.name = '"Embed App Extensions"';
  embedPhase.dstPath = '""';
  embedPhase.dstSubfolderSpec = 13;

  const existingWidgetBuildFileUuids = removeDuplicateWidgetEmbedPhases(
    xcodeProject,
    mainTargetUuid,
    embedPhaseRef.uuid,
    productReference,
  );
  const reusableWidgetBuildFileUuid = existingWidgetBuildFileUuids[0];

  embedPhase.files = (embedPhase.files ?? []).filter((fileRef) => {
    return !isWidgetProductBuildFile(xcodeProject, buildFiles[fileRef.value], productReference);
  });

  const buildFileUuid = reusableWidgetBuildFileUuid ?? xcodeProject.generateUuid();
  const commentKey = `${buildFileUuid}_comment`;
  buildFiles[buildFileUuid] = buildFiles[buildFileUuid] ?? {
    isa: 'PBXBuildFile',
    fileRef: productReference,
    fileRef_comment: `${WIDGET_TARGET_NAME}.appex`,
  };
  buildFiles[buildFileUuid].settings = { ATTRIBUTES: ['RemoveHeadersOnCopy'] };
  buildFiles[commentKey] = `${WIDGET_TARGET_NAME}.appex in Embed App Extensions`;
  embedPhase.files.push({
    value: buildFileUuid,
    comment: `${WIDGET_TARGET_NAME}.appex in Embed App Extensions`,
  });

  for (const buildFileUuidToRemove of existingWidgetBuildFileUuids.slice(1)) {
    delete buildFiles[buildFileUuidToRemove];
    delete buildFiles[`${buildFileUuidToRemove}_comment`];
  }
};

const addWidgetFilesToProject = (xcodeProject, widgetTargetUuid) => {
  const widgetGroup = ensurePbxGroup(xcodeProject, WIDGET_TARGET_NAME);
  ensureResourcesGroup(xcodeProject);

  ensureBuildPhase(xcodeProject, widgetTargetUuid, 'PBXSourcesBuildPhase', 'Sources');
  ensureBuildPhase(xcodeProject, widgetTargetUuid, 'PBXResourcesBuildPhase', 'Resources');
  ensureBuildPhase(xcodeProject, widgetTargetUuid, 'PBXFrameworksBuildPhase', 'Frameworks');

  for (const fileName of WIDGET_GROUP_FILES) {
    if (hasFileReferenceInGroup(xcodeProject, widgetGroup, fileName, WIDGET_TARGET_NAME)) {
      continue;
    }

    if (WIDGET_SWIFT_FILES.includes(fileName)) {
      xcodeProject.addSourceFile(fileName, { target: widgetTargetUuid }, widgetGroup.uuid);
    } else if (fileName === 'Assets.xcassets') {
      xcodeProject.addResourceFile(fileName, { target: widgetTargetUuid }, widgetGroup.uuid);
    } else {
      xcodeProject.addFile(fileName, widgetGroup.uuid);
    }
  }

  for (const framework of ['WidgetKit.framework', 'SwiftUI.framework']) {
    xcodeProject.addFramework(framework, {
      target: widgetTargetUuid,
      weak: false,
      link: true,
    });
  }
};

const addWidgetExtensionToProject = (config, xcodeProject) => {
  const mainTarget = getMainTarget(xcodeProject);
  const mainTargetUuid = mainTarget.uuid ?? mainTarget.value;
  let widgetTarget = getTargetByName(xcodeProject, WIDGET_TARGET_NAME);

  if (!widgetTarget) {
    const addedTarget = xcodeProject.addTarget(
      WIDGET_TARGET_NAME,
      'app_extension',
      WIDGET_TARGET_NAME,
      WIDGET_BUNDLE_ID,
    );
    widgetTarget = { uuid: addedTarget.uuid, nativeTarget: addedTarget.pbxNativeTarget };
  }

  configureWidgetBuildSettings(config, xcodeProject, widgetTarget.uuid, mainTargetUuid);
  addWidgetFilesToProject(xcodeProject, widgetTarget.uuid);
  ensureTargetDependency(xcodeProject, mainTargetUuid, widgetTarget.uuid);
  ensureWidgetEmbeddedInApp(xcodeProject, mainTargetUuid, widgetTarget.uuid);
};

const withNamazymWidgetBridge = (config) => {
  config = withEntitlementsPlist(config, (pluginConfig) => {
    pluginConfig.modResults = ensureAppGroupEntitlement(pluginConfig.modResults);
    return pluginConfig;
  });

  config = withDangerousMod(config, [
    'ios',
    (pluginConfig) => {
      copyBridgeTemplates(pluginConfig.modRequest.projectRoot, pluginConfig.modRequest.platformProjectRoot);
      copyWidgetTemplates(pluginConfig.modRequest.projectRoot, pluginConfig.modRequest.platformProjectRoot);
      patchPodfileForExpoScriptPathSpaces(pluginConfig.modRequest.platformProjectRoot);
      return pluginConfig;
    },
  ]);

  config = withDangerousMod(config, [
    'android',
    (pluginConfig) => {
      copyAndroidWidgetTemplates(pluginConfig.modRequest.projectRoot, pluginConfig.modRequest.platformProjectRoot);
      patchAndroidManifestForWidgets(pluginConfig.modRequest.platformProjectRoot);
      patchAndroidMainApplicationForBridge(pluginConfig.modRequest.platformProjectRoot);
      return pluginConfig;
    },
  ]);

  config = withXcodeProject(config, (pluginConfig) => {
    addBridgeFilesToProject(pluginConfig, pluginConfig.modResults);
    addWidgetExtensionToProject(pluginConfig, pluginConfig.modResults);
    return pluginConfig;
  });

  return config;
};

module.exports = withNamazymWidgetBridge;
