export const TURKMEN_SURAH_NAMES: string[] = [
    "Fatiha", "Bakara", "Äli-Imran", "Nisa", "Maide", "En'am", "A'raf", "Enfal", "Töbe", "Ýunus",
    "Hud", "Ýusup", "Ra'd", "Ybraýym", "Hijr", "Nahl", "Isra", "Kehf", "Merýem", "Taha",
    "Enbiýa", "Haj", "Muminun", "Nur", "Furkan", "Şuara", "Neml", "Kasas", "Ankebut", "Rum",
    "Lukman", "Sejde", "Ahzab", "Sebe", "Fatyr", "Ýasin", "Saffat", "Sad", "Zümer", "Mumin",
    "Fussilet", "Şura", "Zuhruf", "Duhan", "Jäsiýe", "Ahkaf", "Muhammet", "Feth", "Hujurat", "Kaf",
    "Zariýat", "Tur", "Nejm", "Kamer", "Rahman", "Wakyýa", "Hadid", "Mujadele", "Haşr", "Mümtehine",
    "Saff", "Juma", "Munafikun", "Tegabun", "Talak", "Tahrym", "Mülk", "Kalem", "Hakka", "Mearij",
    "Nuh", "Jyn", "Muzzemmil", "Muddessir", "Kyýama", "Ynsan", "Murselat", "Nebe", "Naziýat", "Abese",
    "Tekwir", "Infitar", "Mutaffifiýyn", "Inşikak", "Buruj", "Taryk", "A'la", "Gaşiýe", "Fejr", "Beled",
    "Şems", "Leýl", "Duha", "Inşirah", "Tin", "Alak", "Kadyr", "Beýýine", "Zilzal", "Adyýat",
    "Karyýa", "Tekasur", "Asr", "Humeze", "Fil", "Kureýş", "Maun", "Kewser", "Kafirun", "Nesr",
    "Mesed", "Yhlas", "Felak", "Nas"
];

export const SURAH_NAMES: Record<number, { tm: string; ar: string }> = {
    1: { tm: "Fatiha", ar: "الفاتحة" },
    2: { tm: "Bakara", ar: "البقرة" },
    3: { tm: "Äli-Imran", ar: "آل عمران" },
    4: { tm: "Nisa", ar: "النساء" },
    5: { tm: "Maide", ar: "المائدة" },
    6: { tm: "En'am", ar: "الأنعام" },
    7: { tm: "A'raf", ar: "الأعراف" },
    8: { tm: "Enfal", ar: "الأنفال" },
    9: { tm: "Töbe", ar: "التوبة" },
    10: { tm: "Ýunus", ar: "يونس" },
    11: { tm: "Hud", ar: "هود" },
    12: { tm: "Ýusup", ar: "يوسف" },
    13: { tm: "Ra'd", ar: "الرعد" },
    14: { tm: "Ybraýym", ar: "إبراهيم" },
    15: { tm: "Hijr", ar: "الحجر" },
    16: { tm: "Nahl", ar: "النحل" },
    17: { tm: "Isra", ar: "الإسراء" },
    18: { tm: "Kehf", ar: "الكهف" },
    19: { tm: "Merýem", ar: "مريم" },
    20: { tm: "Taha", ar: "طه" },
    21: { tm: "Enbiýa", ar: "الأنبياء" },
    22: { tm: "Haj", ar: "الحج" },
    23: { tm: "Muminun", ar: "المؤمنون" },
    24: { tm: "Nur", ar: "النور" },
    25: { tm: "Furkan", ar: "الفرقان" },
    26: { tm: "Şuara", ar: "الشعراء" },
    27: { tm: "Neml", ar: "النمل" },
    28: { tm: "Kasas", ar: "القصص" },
    29: { tm: "Ankebut", ar: "العنكبوت" },
    30: { tm: "Rum", ar: "الروم" },
    31: { tm: "Lukman", ar: "لقمان" },
    32: { tm: "Sejde", ar: "السجدة" },
    33: { tm: "Ahzab", ar: "الأحزاب" },
    34: { tm: "Sebe", ar: "سبأ" },
    35: { tm: "Fatyr", ar: "فاطر" },
    36: { tm: "Ýasin", ar: "يس" },
    37: { tm: "Saffat", ar: "الصافات" },
    38: { tm: "Sad", ar: "ص" },
    39: { tm: "Zümer", ar: "الزمر" },
    40: { tm: "Mumin", ar: "غافر" },
    41: { tm: "Fussilet", ar: "فصلت" },
    42: { tm: "Şura", ar: "الشورى" },
    43: { tm: "Zuhruf", ar: "الزخرف" },
    44: { tm: "Duhan", ar: "الدخان" },
    45: { tm: "Jäsiýe", ar: "الجاثية" },
    46: { tm: "Ahkaf", ar: "الأحقاف" },
    47: { tm: "Muhammet", ar: "محمد" },
    48: { tm: "Feth", ar: "الفتح" },
    49: { tm: "Hujurat", ar: "الحجرات" },
    50: { tm: "Kaf", ar: "ق" },
    51: { tm: "Zariýat", ar: "الذاريات" },
    52: { tm: "Tur", ar: "الطور" },
    53: { tm: "Nejm", ar: "النجم" },
    54: { tm: "Kamer", ar: "القمر" },
    55: { tm: "Rahman", ar: "الرحمن" },
    56: { tm: "Wakyýa", ar: "الواقعة" },
    57: { tm: "Hadid", ar: "الحديد" },
    58: { tm: "Mujadele", ar: "المجادلة" },
    59: { tm: "Haşr", ar: "الحشر" },
    60: { tm: "Mümtehine", ar: "الممتحنة" },
    61: { tm: "Saff", ar: "الصف" },
    62: { tm: "Juma", ar: "الجمعة" },
    63: { tm: "Munafikun", ar: "المنافقون" },
    64: { tm: "Tegabun", ar: "التغابن" },
    65: { tm: "Talak", ar: "الطلاق" },
    66: { tm: "Tahrym", ar: "التحريم" },
    67: { tm: "Mülk", ar: "الملك" },
    68: { tm: "Kalem", ar: "القلم" },
    69: { tm: "Hakka", ar: "الحاقة" },
    70: { tm: "Mearij", ar: "المعارج" },
    71: { tm: "Nuh", ar: "نوح" },
    72: { tm: "Jyn", ar: "الجن" },
    73: { tm: "Muzzemmil", ar: "المزمل" },
    74: { tm: "Muddessir", ar: "المدثر" },
    75: { tm: "Kyýama", ar: "القيامة" },
    76: { tm: "Ynsan", ar: "الإنسان" },
    77: { tm: "Murselat", ar: "المرسلات" },
    78: { tm: "Nebe", ar: "النبأ" },
    79: { tm: "Naziýat", ar: "النازعات" },
    80: { tm: "Abese", ar: "عبس" },
    81: { tm: "Tekwir", ar: "التكوير" },
    82: { tm: "Infitar", ar: "الانفطار" },
    83: { tm: "Mutaffifiýyn", ar: "المطففين" },
    84: { tm: "Inşikak", ar: "الانشقاق" },
    85: { tm: "Buruj", ar: "البروج" },
    86: { tm: "Taryk", ar: "الطارق" },
    87: { tm: "A'la", ar: "الأعلى" },
    88: { tm: "Gaşiýe", ar: "الغاشية" },
    89: { tm: "Fejr", ar: "الفجر" },
    90: { tm: "Beled", ar: "البلد" },
    91: { tm: "Şems", ar: "الشمس" },
    92: { tm: "Leýl", ar: "الليل" },
    93: { tm: "Duha", ar: "الضحى" },
    94: { tm: "Inşirah", ar: "الشرح" },
    95: { tm: "Tin", ar: "التين" },
    96: { tm: "Alak", ar: "العلق" },
    97: { tm: "Kadyr", ar: "القدر" },
    98: { tm: "Beýýine", ar: "البينة" },
    99: { tm: "Zilzal", ar: "الزلزلة" },
    100: { tm: "Adyýat", ar: "العاديات" },
    101: { tm: "Karyýa", ar: "القارعة" },
    102: { tm: "Tekasur", ar: "التكاثر" },
    103: { tm: "Asr", ar: "العصر" },
    104: { tm: "Humeze", ar: "الهمزة" },
    105: { tm: "Fil", ar: "الفيل" },
    106: { tm: "Kureýş", ar: "قريش" },
    107: { tm: "Maun", ar: "الماعون" },
    108: { tm: "Kewser", ar: "الكوثر" },
    109: { tm: "Kafirun", ar: "الكافرون" },
    110: { tm: "Nesr", ar: "النصر" },
    111: { tm: "Mesed", ar: "المسد" },
    112: { tm: "Yhlas", ar: "الإخلاص" },
    113: { tm: "Felak", ar: "الفلق" },
    114: { tm: "Nas", ar: "الناس" }
};

export function getReferenceLabel(surah: number, ayah: number) {
    const name = TURKMEN_SURAH_NAMES[surah - 1] || `Süre ${surah}`;
    return `${name} ${ayah}`;
}
